# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bibleimport.ui'
#
# Created: Thu Dec  4 20:52:10 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_BibleImportDialog(object):
    def setupUi(self, BibleImportDialog):
        BibleImportDialog.setObjectName("BibleImportDialog")
        BibleImportDialog.resize(494, 658)
        self.BibleImportButtonBox = QtGui.QDialogButtonBox(BibleImportDialog)
        self.BibleImportButtonBox.setGeometry(QtCore.QRect(10, 620, 481, 33))
        self.BibleImportButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.BibleImportButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.BibleImportButtonBox.setObjectName("BibleImportButtonBox")
        self.ImportToolBox = QtGui.QToolBox(BibleImportDialog)
        self.ImportToolBox.setGeometry(QtCore.QRect(0, 0, 481, 431))
        self.ImportToolBox.setObjectName("ImportToolBox")
        self.FileImportPage = QtGui.QWidget()
        self.FileImportPage.setGeometry(QtCore.QRect(0, 0, 471, 361))
        self.FileImportPage.setObjectName("FileImportPage")
        self.OSISGroupBox = QtGui.QGroupBox(self.FileImportPage)
        self.OSISGroupBox.setGeometry(QtCore.QRect(8, 74, 451, 71))
        self.OSISGroupBox.setObjectName("OSISGroupBox")
        self.OSISLocationEdit = QtGui.QLineEdit(self.OSISGroupBox)
        self.OSISLocationEdit.setGeometry(QtCore.QRect(110, 29, 271, 28))
        self.OSISLocationEdit.setObjectName("OSISLocationEdit")
        self.OsisFileButton = QtGui.QPushButton(self.OSISGroupBox)
        self.OsisFileButton.setGeometry(QtCore.QRect(400, 30, 41, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/import_load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OsisFileButton.setIcon(icon)
        self.OsisFileButton.setObjectName("OsisFileButton")
        self.LocatioLabel = QtGui.QLabel(self.OSISGroupBox)
        self.LocatioLabel.setGeometry(QtCore.QRect(10, 29, 73, 22))
        self.LocatioLabel.setObjectName("LocatioLabel")
        self.CVSGroupBox = QtGui.QGroupBox(self.FileImportPage)
        self.CVSGroupBox.setGeometry(QtCore.QRect(8, 150, 451, 161))
        self.CVSGroupBox.setObjectName("CVSGroupBox")
        self.BooksLocationLabel = QtGui.QLabel(self.CVSGroupBox)
        self.BooksLocationLabel.setGeometry(QtCore.QRect(10, 70, 101, 17))
        self.BooksLocationLabel.setObjectName("BooksLocationLabel")
        self.BooksLocationEdit = QtGui.QLineEdit(self.CVSGroupBox)
        self.BooksLocationEdit.setGeometry(QtCore.QRect(110, 70, 271, 28))
        self.BooksLocationEdit.setObjectName("BooksLocationEdit")
        self.BooksFileButton = QtGui.QPushButton(self.CVSGroupBox)
        self.BooksFileButton.setGeometry(QtCore.QRect(400, 70, 41, 31))
        self.BooksFileButton.setIcon(icon)
        self.BooksFileButton.setObjectName("BooksFileButton")
        self.VerseLocationLabel = QtGui.QLabel(self.CVSGroupBox)
        self.VerseLocationLabel.setGeometry(QtCore.QRect(10, 110, 91, 17))
        self.VerseLocationLabel.setObjectName("VerseLocationLabel")
        self.VerseLocationEdit = QtGui.QLineEdit(self.CVSGroupBox)
        self.VerseLocationEdit.setGeometry(QtCore.QRect(110, 110, 271, 28))
        self.VerseLocationEdit.setObjectName("VerseLocationEdit")
        self.VersesFileButton = QtGui.QPushButton(self.CVSGroupBox)
        self.VersesFileButton.setGeometry(QtCore.QRect(400, 110, 41, 31))
        self.VersesFileButton.setIcon(icon)
        self.VersesFileButton.setObjectName("VersesFileButton")
        self.BibleNameEdit = QtGui.QLineEdit(self.FileImportPage)
        self.BibleNameEdit.setGeometry(QtCore.QRect(120, 20, 271, 28))
        self.BibleNameEdit.setObjectName("BibleNameEdit")
        self.BibleNameLabel = QtGui.QLabel(self.FileImportPage)
        self.BibleNameLabel.setGeometry(QtCore.QRect(18, 20, 98, 22))
        self.BibleNameLabel.setObjectName("BibleNameLabel")
        self.ImportToolBox.addItem(self.FileImportPage, "")
        self.WebBiblePage = QtGui.QWidget()
        self.WebBiblePage.setGeometry(QtCore.QRect(0, 0, 471, 361))
        self.WebBiblePage.setObjectName("WebBiblePage")
        self.WebBibleLayout = QtGui.QVBoxLayout(self.WebBiblePage)
        self.WebBibleLayout.setSpacing(8)
        self.WebBibleLayout.setMargin(8)
        self.WebBibleLayout.setObjectName("WebBibleLayout")
        self.OptionsGroupBox = QtGui.QGroupBox(self.WebBiblePage)
        self.OptionsGroupBox.setObjectName("OptionsGroupBox")
        self.OptionsLayout = QtGui.QFormLayout(self.OptionsGroupBox)
        self.OptionsLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.OptionsLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OptionsLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OptionsLayout.setMargin(8)
        self.OptionsLayout.setSpacing(8)
        self.OptionsLayout.setObjectName("OptionsLayout")
        self.LocationLabel = QtGui.QLabel(self.OptionsGroupBox)
        self.LocationLabel.setObjectName("LocationLabel")
        self.OptionsLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.LocationLabel)
        self.LocationComboBox = QtGui.QComboBox(self.OptionsGroupBox)
        self.LocationComboBox.setObjectName("LocationComboBox")
        self.LocationComboBox.addItem(QtCore.QString())
        self.LocationComboBox.addItem(QtCore.QString())
        self.OptionsLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LocationComboBox)
        self.TypeLabel = QtGui.QLabel(self.OptionsGroupBox)
        self.TypeLabel.setObjectName("TypeLabel")
        self.OptionsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.TypeLabel)
        self.TypeComboBox = QtGui.QComboBox(self.OptionsGroupBox)
        self.TypeComboBox.setObjectName("TypeComboBox")
        self.TypeComboBox.addItem(QtCore.QString())
        self.TypeComboBox.addItem(QtCore.QString())
        self.OptionsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.TypeComboBox)
        self.BibleLabel = QtGui.QLabel(self.OptionsGroupBox)
        self.BibleLabel.setObjectName("BibleLabel")
        self.OptionsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.BibleLabel)
        self.BibleComboBox = QtGui.QComboBox(self.OptionsGroupBox)
        self.BibleComboBox.setObjectName("BibleComboBox")
        self.BibleComboBox.addItem(QtCore.QString())
        self.BibleComboBox.addItem(QtCore.QString())
        self.OptionsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.BibleComboBox)
        self.WebBibleLayout.addWidget(self.OptionsGroupBox)
        self.ProxyGroupBox = QtGui.QGroupBox(self.WebBiblePage)
        self.ProxyGroupBox.setObjectName("ProxyGroupBox")
        self.ProxySettingsLayout = QtGui.QFormLayout(self.ProxyGroupBox)
        self.ProxySettingsLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.ProxySettingsLayout.setMargin(8)
        self.ProxySettingsLayout.setSpacing(8)
        self.ProxySettingsLayout.setObjectName("ProxySettingsLayout")
        self.AddressLabel = QtGui.QLabel(self.ProxyGroupBox)
        self.AddressLabel.setObjectName("AddressLabel")
        self.ProxySettingsLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.AddressLabel)
        self.AddressEdit = QtGui.QLineEdit(self.ProxyGroupBox)
        self.AddressEdit.setObjectName("AddressEdit")
        self.ProxySettingsLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.AddressEdit)
        self.UsernameLabel = QtGui.QLabel(self.ProxyGroupBox)
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.ProxySettingsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.UsernameLabel)
        self.UsernameEdit = QtGui.QLineEdit(self.ProxyGroupBox)
        self.UsernameEdit.setObjectName("UsernameEdit")
        self.ProxySettingsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.UsernameEdit)
        self.PasswordLabel = QtGui.QLabel(self.ProxyGroupBox)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.ProxySettingsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.PasswordLabel)
        self.PasswordEdit = QtGui.QLineEdit(self.ProxyGroupBox)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.ProxySettingsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.PasswordEdit)
        self.WebBibleLayout.addWidget(self.ProxyGroupBox)
        self.ImportToolBox.addItem(self.WebBiblePage, "")
        self.LicenceDetailsGroupBox = QtGui.QGroupBox(BibleImportDialog)
        self.LicenceDetailsGroupBox.setGeometry(QtCore.QRect(8, 450, 481, 136))
        self.LicenceDetailsGroupBox.setMinimumSize(QtCore.QSize(0, 123))
        self.LicenceDetailsGroupBox.setObjectName("LicenceDetailsGroupBox")
        self.formLayout = QtGui.QFormLayout(self.LicenceDetailsGroupBox)
        self.formLayout.setMargin(8)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.VersionNameLabel = QtGui.QLabel(self.LicenceDetailsGroupBox)
        self.VersionNameLabel.setObjectName("VersionNameLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.VersionNameLabel)
        self.VersionNameEdit = QtGui.QLineEdit(self.LicenceDetailsGroupBox)
        self.VersionNameEdit.setObjectName("VersionNameEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.VersionNameEdit)
        self.CopyrightLabel = QtGui.QLabel(self.LicenceDetailsGroupBox)
        self.CopyrightLabel.setObjectName("CopyrightLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.CopyrightLabel)
        self.CopyrightEdit = QtGui.QLineEdit(self.LicenceDetailsGroupBox)
        self.CopyrightEdit.setObjectName("CopyrightEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.CopyrightEdit)
        self.PermisionLabel = QtGui.QLabel(self.LicenceDetailsGroupBox)
        self.PermisionLabel.setObjectName("PermisionLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.PermisionLabel)
        self.PermisionEdit = QtGui.QLineEdit(self.LicenceDetailsGroupBox)
        self.PermisionEdit.setObjectName("PermisionEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.PermisionEdit)
        self.StatusLabel = QtGui.QLabel(BibleImportDialog)
        self.StatusLabel.setGeometry(QtCore.QRect(10, 590, 54, 17))
        self.StatusLabel.setObjectName("StatusLabel")

        self.retranslateUi(BibleImportDialog)
        self.ImportToolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BibleImportDialog)

    def retranslateUi(self, BibleImportDialog):
        BibleImportDialog.setWindowTitle(QtGui.QApplication.translate("BibleImportDialog", "Bible Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.OSISGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "OSIS Bible", None, QtGui.QApplication.UnicodeUTF8))
        self.LocatioLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "File Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.CVSGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "CVS Bible", None, QtGui.QApplication.UnicodeUTF8))
        self.BooksLocationLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Books Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.BooksFileButton.setText(QtGui.QApplication.translate("BibleImportDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseLocationLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Verse Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.VersesFileButton.setText(QtGui.QApplication.translate("BibleImportDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleNameLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Bible Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportToolBox.setItemText(self.ImportToolBox.indexOf(self.FileImportPage), QtGui.QApplication.translate("BibleImportDialog", "File Import Page", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionsGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "Download Options", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationComboBox.setItemText(0, QtGui.QApplication.translate("BibleImportDialog", "BibleGateway", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationComboBox.setItemText(1, QtGui.QApplication.translate("BibleImportDialog", "CrossWire", None, QtGui.QApplication.UnicodeUTF8))
        self.TypeLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.TypeComboBox.setItemText(0, QtGui.QApplication.translate("BibleImportDialog", "Download As Needed", None, QtGui.QApplication.UnicodeUTF8))
        self.TypeComboBox.setItemText(1, QtGui.QApplication.translate("BibleImportDialog", "Download All", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Bible:", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleComboBox.setItemText(0, QtGui.QApplication.translate("BibleImportDialog", "NIV", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleComboBox.setItemText(1, QtGui.QApplication.translate("BibleImportDialog", "KJV", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "Proxy Settings (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.AddressLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Proxy Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.UsernameLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.PasswordLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportToolBox.setItemText(self.ImportToolBox.indexOf(self.WebBiblePage), QtGui.QApplication.translate("BibleImportDialog", "Web Bible Import page", None, QtGui.QApplication.UnicodeUTF8))
        self.LicenceDetailsGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "Licence Details", None, QtGui.QApplication.UnicodeUTF8))
        self.VersionNameLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Version Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.CopyrightLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Copyright:", None, QtGui.QApplication.UnicodeUTF8))
        self.PermisionLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Permission:", None, QtGui.QApplication.UnicodeUTF8))
        self.StatusLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

