# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bibleimport.ui'
#
# Created: Sat Nov 29 13:19:21 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_BibleImportDialog(object):
    def setupUi(self, BibleImportDialog):
        BibleImportDialog.setObjectName("BibleImportDialog")
        BibleImportDialog.resize(494, 734)
        self.BibleImportButtonBox = QtGui.QDialogButtonBox(BibleImportDialog)
        self.BibleImportButtonBox.setGeometry(QtCore.QRect(10, 690, 481, 33))
        self.BibleImportButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.BibleImportButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.BibleImportButtonBox.setObjectName("BibleImportButtonBox")
        self.ImportToolBox = QtGui.QToolBox(BibleImportDialog)
        self.ImportToolBox.setGeometry(QtCore.QRect(0, 0, 481, 431))
        self.ImportToolBox.setObjectName("ImportToolBox")
        self.CSVImportPage = QtGui.QWidget()
        self.CSVImportPage.setGeometry(QtCore.QRect(0, 0, 481, 338))
        self.CSVImportPage.setObjectName("CSVImportPage")
        self.groupBox_2 = QtGui.QGroupBox(self.CSVImportPage)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 451, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.BibleNameLabel = QtGui.QLabel(self.groupBox_2)
        self.BibleNameLabel.setGeometry(QtCore.QRect(20, 30, 71, 17))
        self.BibleNameLabel.setObjectName("BibleNameLabel")
        self.BibleNameEdit = QtGui.QLineEdit(self.groupBox_2)
        self.BibleNameEdit.setGeometry(QtCore.QRect(110, 30, 271, 28))
        self.BibleNameEdit.setObjectName("BibleNameEdit")
        self.BooksLocationLabel = QtGui.QLabel(self.groupBox_2)
        self.BooksLocationLabel.setGeometry(QtCore.QRect(10, 70, 101, 17))
        self.BooksLocationLabel.setObjectName("BooksLocationLabel")
        self.BooksLocationEdit = QtGui.QLineEdit(self.groupBox_2)
        self.BooksLocationEdit.setGeometry(QtCore.QRect(110, 70, 271, 28))
        self.BooksLocationEdit.setObjectName("BooksLocationEdit")
        self.BooksFileButton = QtGui.QPushButton(self.groupBox_2)
        self.BooksFileButton.setGeometry(QtCore.QRect(390, 70, 41, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/import_load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BooksFileButton.setIcon(icon)
        self.BooksFileButton.setObjectName("BooksFileButton")
        self.VerseLocationLabel = QtGui.QLabel(self.groupBox_2)
        self.VerseLocationLabel.setGeometry(QtCore.QRect(10, 110, 91, 17))
        self.VerseLocationLabel.setObjectName("VerseLocationLabel")
        self.VerseLocationEdit = QtGui.QLineEdit(self.groupBox_2)
        self.VerseLocationEdit.setGeometry(QtCore.QRect(110, 110, 271, 28))
        self.VerseLocationEdit.setObjectName("VerseLocationEdit")
        self.VersesFileButton = QtGui.QPushButton(self.groupBox_2)
        self.VersesFileButton.setGeometry(QtCore.QRect(390, 110, 41, 31))
        self.VersesFileButton.setIcon(icon)
        self.VersesFileButton.setObjectName("VersesFileButton")
        self.ImportToolBox.addItem(self.CSVImportPage, "")
        self.OSISImportPage = QtGui.QWidget()
        self.OSISImportPage.setGeometry(QtCore.QRect(0, 0, 481, 338))
        self.OSISImportPage.setObjectName("OSISImportPage")
        self.groupBox = QtGui.QGroupBox(self.OSISImportPage)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 135))
        self.groupBox.setObjectName("groupBox")
        self.OSISBibleNameEdit = QtGui.QLineEdit(self.groupBox)
        self.OSISBibleNameEdit.setGeometry(QtCore.QRect(119, 39, 271, 28))
        self.OSISBibleNameEdit.setObjectName("OSISBibleNameEdit")
        self.OSISLocationEdit = QtGui.QLineEdit(self.groupBox)
        self.OSISLocationEdit.setGeometry(QtCore.QRect(119, 69, 271, 28))
        self.OSISLocationEdit.setObjectName("OSISLocationEdit")
        self.OsisFileButton = QtGui.QPushButton(self.groupBox)
        self.OsisFileButton.setGeometry(QtCore.QRect(400, 70, 41, 31))
        self.OsisFileButton.setIcon(icon)
        self.OsisFileButton.setObjectName("OsisFileButton")
        self.LocatioLabel = QtGui.QLabel(self.groupBox)
        self.LocatioLabel.setGeometry(QtCore.QRect(13, 69, 73, 22))
        self.LocatioLabel.setObjectName("LocatioLabel")
        self.OSISNameLabel = QtGui.QLabel(self.groupBox)
        self.OSISNameLabel.setGeometry(QtCore.QRect(13, 39, 98, 22))
        self.OSISNameLabel.setObjectName("OSISNameLabel")
        self.ImportToolBox.addItem(self.OSISImportPage, "")
        self.WebBiblePage = QtGui.QWidget()
        self.WebBiblePage.setGeometry(QtCore.QRect(0, 0, 481, 338))
        self.WebBiblePage.setObjectName("WebBiblePage")
        self.WebBibleLayout = QtGui.QVBoxLayout(self.WebBiblePage)
        self.WebBibleLayout.setSpacing(8)
        self.WebBibleLayout.setMargin(8)
        self.WebBibleLayout.setObjectName("WebBibleLayout")
        self.OptionsGroupBox = QtGui.QGroupBox(self.WebBiblePage)
        self.OptionsGroupBox.setObjectName("OptionsGroupBox")
        self.OptionsLayout = QtGui.QFormLayout(self.OptionsGroupBox)
        self.OptionsLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.OptionsLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OptionsLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.OptionsLayout.setMargin(8)
        self.OptionsLayout.setSpacing(8)
        self.OptionsLayout.setObjectName("OptionsLayout")
        self.LocationLabel = QtGui.QLabel(self.OptionsGroupBox)
        self.LocationLabel.setObjectName("LocationLabel")
        self.OptionsLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.LocationLabel)
        self.LocationComboBox = QtGui.QComboBox(self.OptionsGroupBox)
        self.LocationComboBox.setObjectName("LocationComboBox")
        self.LocationComboBox.addItem(QtCore.QString())
        self.LocationComboBox.addItem(QtCore.QString())
        self.OptionsLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LocationComboBox)
        self.TypeLabel = QtGui.QLabel(self.OptionsGroupBox)
        self.TypeLabel.setObjectName("TypeLabel")
        self.OptionsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.TypeLabel)
        self.TypeComboBox = QtGui.QComboBox(self.OptionsGroupBox)
        self.TypeComboBox.setObjectName("TypeComboBox")
        self.TypeComboBox.addItem(QtCore.QString())
        self.TypeComboBox.addItem(QtCore.QString())
        self.OptionsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.TypeComboBox)
        self.BibleLabel = QtGui.QLabel(self.OptionsGroupBox)
        self.BibleLabel.setObjectName("BibleLabel")
        self.OptionsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.BibleLabel)
        self.BibleComboBox = QtGui.QComboBox(self.OptionsGroupBox)
        self.BibleComboBox.setObjectName("BibleComboBox")
        self.BibleComboBox.addItem(QtCore.QString())
        self.BibleComboBox.addItem(QtCore.QString())
        self.OptionsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.BibleComboBox)
        self.WebBibleLayout.addWidget(self.OptionsGroupBox)
        self.ProxyGroupBox = QtGui.QGroupBox(self.WebBiblePage)
        self.ProxyGroupBox.setObjectName("ProxyGroupBox")
        self.ProxySettingsLayout = QtGui.QFormLayout(self.ProxyGroupBox)
        self.ProxySettingsLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.ProxySettingsLayout.setMargin(8)
        self.ProxySettingsLayout.setSpacing(8)
        self.ProxySettingsLayout.setObjectName("ProxySettingsLayout")
        self.AddressLabel = QtGui.QLabel(self.ProxyGroupBox)
        self.AddressLabel.setObjectName("AddressLabel")
        self.ProxySettingsLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.AddressLabel)
        self.AddressEdit = QtGui.QLineEdit(self.ProxyGroupBox)
        self.AddressEdit.setObjectName("AddressEdit")
        self.ProxySettingsLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.AddressEdit)
        self.UsernameLabel = QtGui.QLabel(self.ProxyGroupBox)
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.ProxySettingsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.UsernameLabel)
        self.UsernameEdit = QtGui.QLineEdit(self.ProxyGroupBox)
        self.UsernameEdit.setObjectName("UsernameEdit")
        self.ProxySettingsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.UsernameEdit)
        self.PasswordLabel = QtGui.QLabel(self.ProxyGroupBox)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.ProxySettingsLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.PasswordLabel)
        self.PasswordEdit = QtGui.QLineEdit(self.ProxyGroupBox)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.ProxySettingsLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.PasswordEdit)
        self.WebBibleLayout.addWidget(self.ProxyGroupBox)
        self.ImportToolBox.addItem(self.WebBiblePage, "")
        self.LicenceDetailsGroupBox = QtGui.QGroupBox(BibleImportDialog)
        self.LicenceDetailsGroupBox.setGeometry(QtCore.QRect(10, 450, 481, 136))
        self.LicenceDetailsGroupBox.setMinimumSize(QtCore.QSize(0, 123))
        self.LicenceDetailsGroupBox.setObjectName("LicenceDetailsGroupBox")
        self.formLayout = QtGui.QFormLayout(self.LicenceDetailsGroupBox)
        self.formLayout.setMargin(8)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.VersionNameLabel = QtGui.QLabel(self.LicenceDetailsGroupBox)
        self.VersionNameLabel.setObjectName("VersionNameLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.VersionNameLabel)
        self.VersionNameEdit = QtGui.QLineEdit(self.LicenceDetailsGroupBox)
        self.VersionNameEdit.setObjectName("VersionNameEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.VersionNameEdit)
        self.CopyrightLabel = QtGui.QLabel(self.LicenceDetailsGroupBox)
        self.CopyrightLabel.setObjectName("CopyrightLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.CopyrightLabel)
        self.CopyrightEdit = QtGui.QLineEdit(self.LicenceDetailsGroupBox)
        self.CopyrightEdit.setObjectName("CopyrightEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.CopyrightEdit)
        self.PermisionLabel = QtGui.QLabel(self.LicenceDetailsGroupBox)
        self.PermisionLabel.setObjectName("PermisionLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.PermisionLabel)
        self.PermisionEdit = QtGui.QLineEdit(self.LicenceDetailsGroupBox)
        self.PermisionEdit.setObjectName("PermisionEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.PermisionEdit)
        self.ProgressGroupBox = QtGui.QGroupBox(BibleImportDialog)
        self.ProgressGroupBox.setGeometry(QtCore.QRect(10, 590, 481, 92))
        self.ProgressGroupBox.setObjectName("ProgressGroupBox")
        self.ProgressLayout = QtGui.QFormLayout(self.ProgressGroupBox)
        self.ProgressLayout.setMargin(8)
        self.ProgressLayout.setSpacing(8)
        self.ProgressLayout.setObjectName("ProgressLayout")
        self.ProgressStatusLabel = QtGui.QLabel(self.ProgressGroupBox)
        self.ProgressStatusLabel.setObjectName("ProgressStatusLabel")
        self.ProgressLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ProgressStatusLabel)
        self.progressBar = QtGui.QProgressBar(self.ProgressGroupBox)
        self.progressBar.setProperty("value", QtCore.QVariant(24))
        self.progressBar.setObjectName("progressBar")
        self.ProgressLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.progressBar)

        self.retranslateUi(BibleImportDialog)
        self.ImportToolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.BibleImportButtonBox, QtCore.SIGNAL("accepted()"), BibleImportDialog.accept)
        QtCore.QObject.connect(self.BibleImportButtonBox, QtCore.SIGNAL("rejected()"), BibleImportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BibleImportDialog)

    def retranslateUi(self, BibleImportDialog):
        BibleImportDialog.setWindowTitle(QtGui.QApplication.translate("BibleImportDialog", "Bible Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BibleImportDialog", "CVS Bible", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleNameLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Bible Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.BooksLocationLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Books Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.BooksFileButton.setText(QtGui.QApplication.translate("BibleImportDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseLocationLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Verse Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.VersesFileButton.setText(QtGui.QApplication.translate("BibleImportDialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportToolBox.setItemText(self.ImportToolBox.indexOf(self.CSVImportPage), QtGui.QApplication.translate("BibleImportDialog", "CVS File Import", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "OSIS Bible", None, QtGui.QApplication.UnicodeUTF8))
        self.LocatioLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "File Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.OSISNameLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "OSIS Bible Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportToolBox.setItemText(self.ImportToolBox.indexOf(self.OSISImportPage), QtGui.QApplication.translate("BibleImportDialog", "OSIS XML Bible Import", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionsGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "Download Options", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationComboBox.setItemText(0, QtGui.QApplication.translate("BibleImportDialog", "BibleGateway", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationComboBox.setItemText(1, QtGui.QApplication.translate("BibleImportDialog", "CrossWire", None, QtGui.QApplication.UnicodeUTF8))
        self.TypeLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.TypeComboBox.setItemText(0, QtGui.QApplication.translate("BibleImportDialog", "Download As Needed", None, QtGui.QApplication.UnicodeUTF8))
        self.TypeComboBox.setItemText(1, QtGui.QApplication.translate("BibleImportDialog", "Download All", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Bible:", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleComboBox.setItemText(0, QtGui.QApplication.translate("BibleImportDialog", "NIV", None, QtGui.QApplication.UnicodeUTF8))
        self.BibleComboBox.setItemText(1, QtGui.QApplication.translate("BibleImportDialog", "KJV", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxyGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "Proxy Settings (Optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.AddressLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Proxy Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.UsernameLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.PasswordLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportToolBox.setItemText(self.ImportToolBox.indexOf(self.WebBiblePage), QtGui.QApplication.translate("BibleImportDialog", "Web Bible Download", None, QtGui.QApplication.UnicodeUTF8))
        self.LicenceDetailsGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "Licence Details", None, QtGui.QApplication.UnicodeUTF8))
        self.VersionNameLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Version Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.CopyrightLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Copyright:", None, QtGui.QApplication.UnicodeUTF8))
        self.PermisionLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "Permission:", None, QtGui.QApplication.UnicodeUTF8))
        self.ProgressGroupBox.setTitle(QtGui.QApplication.translate("BibleImportDialog", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.ProgressStatusLabel.setText(QtGui.QApplication.translate("BibleImportDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

