# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editcustomdialog.ui'
#
# Created: Sat Mar  7 09:01:43 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from openlp.core import translate

class Ui_customEditDialog(object):
    def setupUi(self, customEditDialog):
        customEditDialog.setObjectName("customEditDialog")
        customEditDialog.resize(590, 541)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/openlp.org-icon-32.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        customEditDialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(customEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel = QtGui.QLabel(customEditDialog)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        self.TitleEdit = QtGui.QLineEdit(customEditDialog)
        self.TitleEdit.setObjectName("TitleEdit")
        self.horizontalLayout.addWidget(self.TitleEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.VerseListView = QtGui.QListWidget(customEditDialog)
        self.VerseListView.setObjectName("VerseListView")
        self.horizontalLayout_4.addWidget(self.VerseListView)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.UpButton = QtGui.QPushButton(customEditDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/services/service_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpButton.setIcon(icon1)
        self.UpButton.setObjectName("UpButton")
        self.verticalLayout.addWidget(self.UpButton)
        spacerItem = QtGui.QSpacerItem(20, 128, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.DownButton = QtGui.QPushButton(customEditDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/services/service_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DownButton.setIcon(icon2)
        self.DownButton.setObjectName("DownButton")
        self.verticalLayout.addWidget(self.DownButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.EditWidget = QtGui.QWidget(customEditDialog)
        self.EditWidget.setObjectName("EditWidget")
        self.EditLayout = QtGui.QHBoxLayout(self.EditWidget)
        self.EditLayout.setSpacing(8)
        self.EditLayout.setMargin(0)
        self.EditLayout.setObjectName("EditLayout")
        self.VerseTextEdit = QtGui.QTextEdit(self.EditWidget)
        self.VerseTextEdit.setObjectName("VerseTextEdit")
        self.EditLayout.addWidget(self.VerseTextEdit)
        self.ButtonWidget = QtGui.QWidget(self.EditWidget)
        self.ButtonWidget.setObjectName("ButtonWidget")
        self.ButtonLayout = QtGui.QVBoxLayout(self.ButtonWidget)
        self.ButtonLayout.setSpacing(8)
        self.ButtonLayout.setMargin(0)
        self.ButtonLayout.setObjectName("ButtonLayout")
        self.AddButton = QtGui.QPushButton(self.ButtonWidget)
        self.AddButton.setObjectName("AddButton")
        self.ButtonLayout.addWidget(self.AddButton)
        self.EditButton = QtGui.QPushButton(self.ButtonWidget)
        self.EditButton.setObjectName("EditButton")
        self.ButtonLayout.addWidget(self.EditButton)
        self.SaveButton = QtGui.QPushButton(self.ButtonWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.ButtonLayout.addWidget(self.SaveButton)
        self.DeleteButton = QtGui.QPushButton(self.ButtonWidget)
        self.DeleteButton.setObjectName("DeleteButton")
        self.ButtonLayout.addWidget(self.DeleteButton)
        self.ClearButton = QtGui.QPushButton(self.ButtonWidget)
        self.ClearButton.setObjectName("ClearButton")
        self.ButtonLayout.addWidget(self.ClearButton)           
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.ButtonLayout.addItem(spacerItem1)
        self.EditLayout.addWidget(self.ButtonWidget)
        self.gridLayout.addWidget(self.EditWidget, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ThemeLabel = QtGui.QLabel(customEditDialog)
        self.ThemeLabel.setObjectName("ThemeLabel")
        self.horizontalLayout.addWidget(self.ThemeLabel)
        self.ThemecomboBox = QtGui.QComboBox(customEditDialog)
        self.ThemecomboBox.setObjectName("ThemecomboBox")
        self.horizontalLayout.addWidget(self.ThemecomboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CreditLabel = QtGui.QLabel(customEditDialog)
        self.CreditLabel.setObjectName("CreditLabel")
        self.horizontalLayout_2.addWidget(self.CreditLabel)
        self.CreditEdit = QtGui.QLineEdit(customEditDialog)
        self.CreditEdit.setObjectName("CreditEdit")
        self.horizontalLayout_2.addWidget(self.CreditEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(customEditDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 1)

        self.retranslateUi(customEditDialog)
        QtCore.QMetaObject.connectSlotsByName(customEditDialog)
        customEditDialog.setTabOrder(self.TitleEdit, self.VerseTextEdit)
        customEditDialog.setTabOrder(self.VerseTextEdit, self.EditButton)
        customEditDialog.setTabOrder(self.EditButton, self.SaveButton)
        customEditDialog.setTabOrder(self.SaveButton, self.CreditEdit)
        customEditDialog.setTabOrder(self.CreditEdit, self.VerseListView)
        customEditDialog.setTabOrder(self.VerseListView, self.AddButton)
        customEditDialog.setTabOrder(self.AddButton, self.DeleteButton)
        customEditDialog.setTabOrder(self.DeleteButton, self.buttonBox)
    
    def retranslateUi(self, customEditDialog):
        customEditDialog.setWindowTitle(translate("customEditDialog", "Edit Custom Slides"))
        self.TitleLabel.setText(translate("customEditDialog", "Title:"))
        self.AddButton.setText(translate("customEditDialog", "Add"))
        self.EditButton.setText(translate("customEditDialog", "Edit"))
        self.SaveButton.setText(translate("customEditDialog", "Save"))
        self.DeleteButton.setText(translate("customEditDialog", "Delete"))
        self.ClearButton.setText(translate("customEditDialog", "Clear"))
        self.ThemeLabel.setText(translate("customEditDialog", "Theme:"))
        self.CreditLabel.setText(translate("customEditDialog", "Credits:"))
