# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'amendthemedialog.ui'
#
# Created: Tue Apr 21 06:06:56 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AmendThemeDialog(object):
    def setupUi(self, AmendThemeDialog):
        AmendThemeDialog.setObjectName("AmendThemeDialog")
        AmendThemeDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        AmendThemeDialog.resize(586, 651)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/openlp-logo-16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AmendThemeDialog.setWindowIcon(icon)
        AmendThemeDialog.setModal(True)
        self.AmendThemeLayout = QtGui.QVBoxLayout(AmendThemeDialog)
        self.AmendThemeLayout.setSpacing(8)
        self.AmendThemeLayout.setMargin(8)
        self.AmendThemeLayout.setObjectName("AmendThemeLayout")
        self.ThemeNameWidget = QtGui.QWidget(AmendThemeDialog)
        self.ThemeNameWidget.setObjectName("ThemeNameWidget")
        self.ThemeNameLayout = QtGui.QHBoxLayout(self.ThemeNameWidget)
        self.ThemeNameLayout.setSpacing(8)
        self.ThemeNameLayout.setMargin(0)
        self.ThemeNameLayout.setObjectName("ThemeNameLayout")
        self.ThemeNameLabel = QtGui.QLabel(self.ThemeNameWidget)
        self.ThemeNameLabel.setObjectName("ThemeNameLabel")
        self.ThemeNameLayout.addWidget(self.ThemeNameLabel)
        self.ThemeNameEdit = QtGui.QLineEdit(self.ThemeNameWidget)
        self.ThemeNameEdit.setObjectName("ThemeNameEdit")
        self.ThemeNameLayout.addWidget(self.ThemeNameEdit)
        self.AmendThemeLayout.addWidget(self.ThemeNameWidget)
        self.ContentWidget = QtGui.QWidget(AmendThemeDialog)
        self.ContentWidget.setObjectName("ContentWidget")
        self.ContentLayout = QtGui.QHBoxLayout(self.ContentWidget)
        self.ContentLayout.setSpacing(8)
        self.ContentLayout.setMargin(0)
        self.ContentLayout.setObjectName("ContentLayout")
        self.ThemeTabWidget = QtGui.QTabWidget(self.ContentWidget)
        self.ThemeTabWidget.setObjectName("ThemeTabWidget")
        self.BackgroundTab = QtGui.QWidget()
        self.BackgroundTab.setObjectName("BackgroundTab")
        self.BackgroundLayout = QtGui.QFormLayout(self.BackgroundTab)
        self.BackgroundLayout.setMargin(8)
        self.BackgroundLayout.setSpacing(8)
        self.BackgroundLayout.setObjectName("BackgroundLayout")
        self.BackgroundLabel = QtGui.QLabel(self.BackgroundTab)
        self.BackgroundLabel.setObjectName("BackgroundLabel")
        self.BackgroundLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.BackgroundLabel)
        self.BackgroundComboBox = QtGui.QComboBox(self.BackgroundTab)
        self.BackgroundComboBox.setObjectName("BackgroundComboBox")
        self.BackgroundComboBox.addItem(QtCore.QString())
        self.BackgroundComboBox.addItem(QtCore.QString())
        self.BackgroundLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.BackgroundComboBox)
        self.BackgroundTypeLabel = QtGui.QLabel(self.BackgroundTab)
        self.BackgroundTypeLabel.setObjectName("BackgroundTypeLabel")
        self.BackgroundLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.BackgroundTypeLabel)
        self.BackgroundTypeComboBox = QtGui.QComboBox(self.BackgroundTab)
        self.BackgroundTypeComboBox.setObjectName("BackgroundTypeComboBox")
        self.BackgroundTypeComboBox.addItem(QtCore.QString())
        self.BackgroundTypeComboBox.addItem(QtCore.QString())
        self.BackgroundTypeComboBox.addItem(QtCore.QString())
        self.BackgroundLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.BackgroundTypeComboBox)
        self.Color1Label = QtGui.QLabel(self.BackgroundTab)
        self.Color1Label.setObjectName("Color1Label")
        self.BackgroundLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Color1Label)
        self.Color1PushButton = QtGui.QPushButton(self.BackgroundTab)
        self.Color1PushButton.setObjectName("Color1PushButton")
        self.BackgroundLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Color1PushButton)
        self.Color2Label = QtGui.QLabel(self.BackgroundTab)
        self.Color2Label.setObjectName("Color2Label")
        self.BackgroundLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.Color2Label)
        self.Color2PushButton = QtGui.QPushButton(self.BackgroundTab)
        self.Color2PushButton.setObjectName("Color2PushButton")
        self.BackgroundLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.Color2PushButton)
        self.ImageLabel = QtGui.QLabel(self.BackgroundTab)
        self.ImageLabel.setObjectName("ImageLabel")
        self.BackgroundLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.ImageLabel)
        self.GradientLabel = QtGui.QLabel(self.BackgroundTab)
        self.GradientLabel.setObjectName("GradientLabel")
        self.BackgroundLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.GradientLabel)
        self.GradientComboBox = QtGui.QComboBox(self.BackgroundTab)
        self.GradientComboBox.setObjectName("GradientComboBox")
        self.GradientComboBox.addItem(QtCore.QString())
        self.GradientComboBox.addItem(QtCore.QString())
        self.GradientComboBox.addItem(QtCore.QString())
        self.BackgroundLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.GradientComboBox)
        self.ImageFilenameWidget = QtGui.QWidget(self.BackgroundTab)
        self.ImageFilenameWidget.setObjectName("ImageFilenameWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ImageFilenameWidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImageLineEdit = QtGui.QLineEdit(self.ImageFilenameWidget)
        self.ImageLineEdit.setObjectName("ImageLineEdit")
        self.horizontalLayout_2.addWidget(self.ImageLineEdit)
        self.ImageToolButton = QtGui.QToolButton(self.ImageFilenameWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/image_load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ImageToolButton.setIcon(icon1)
        self.ImageToolButton.setObjectName("ImageToolButton")
        self.horizontalLayout_2.addWidget(self.ImageToolButton)
        self.BackgroundLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ImageFilenameWidget)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        #self.BackgroundLayout.addItem(spacerItem, 7, 1, 1, 1)
        self.ThemeTabWidget.addTab(self.BackgroundTab, "")
        self.FontMainTab = QtGui.QWidget()
        self.FontMainTab.setObjectName("FontMainTab")
        self.FontMainLayout = QtGui.QHBoxLayout(self.FontMainTab)
        self.FontMainLayout.setSpacing(8)
        self.FontMainLayout.setMargin(8)
        self.FontMainLayout.setObjectName("FontMainLayout")
        self.MainLeftWidget = QtGui.QWidget(self.FontMainTab)
        self.MainLeftWidget.setObjectName("MainLeftWidget")
        self.MainLeftLayout = QtGui.QVBoxLayout(self.MainLeftWidget)
        self.MainLeftLayout.setSpacing(8)
        self.MainLeftLayout.setMargin(0)
        self.MainLeftLayout.setObjectName("MainLeftLayout")
        self.FontMainGroupBox = QtGui.QGroupBox(self.MainLeftWidget)
        self.FontMainGroupBox.setObjectName("FontMainGroupBox")
        self.MainFontLayout = QtGui.QFormLayout(self.FontMainGroupBox)
        self.MainFontLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.MainFontLayout.setMargin(8)
        self.MainFontLayout.setSpacing(8)
        self.MainFontLayout.setObjectName("MainFontLayout")
        self.FontMainlabel = QtGui.QLabel(self.FontMainGroupBox)
        self.FontMainlabel.setObjectName("FontMainlabel")
        self.MainFontLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.FontMainlabel)
        self.FontMainComboBox = QtGui.QFontComboBox(self.FontMainGroupBox)
        self.FontMainComboBox.setObjectName("FontMainComboBox")
        self.MainFontLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.FontMainComboBox)
        self.FontMainColorLabel = QtGui.QLabel(self.FontMainGroupBox)
        self.FontMainColorLabel.setObjectName("FontMainColorLabel")
        self.MainFontLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.FontMainColorLabel)
        self.FontMainColorPushButton = QtGui.QPushButton(self.FontMainGroupBox)
        self.FontMainColorPushButton.setObjectName("FontMainColorPushButton")
        self.MainFontLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.FontMainColorPushButton)
        self.FontMainSize = QtGui.QLabel(self.FontMainGroupBox)
        self.FontMainSize.setObjectName("FontMainSize")
        self.MainFontLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.FontMainSize)
        self.FontMainSizeSpinBox = QtGui.QSpinBox(self.FontMainGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontMainSizeSpinBox.sizePolicy().hasHeightForWidth())
        self.FontMainSizeSpinBox.setSizePolicy(sizePolicy)
        self.FontMainSizeSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.FontMainSizeSpinBox.setProperty("value", QtCore.QVariant(16))
        self.FontMainSizeSpinBox.setMaximum(999)
        self.FontMainSizeSpinBox.setObjectName("FontMainSizeSpinBox")
        self.MainFontLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.FontMainSizeSpinBox)
        self.MainLeftLayout.addWidget(self.FontMainGroupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.MainLeftLayout.addItem(spacerItem1)
        self.FontMainLayout.addWidget(self.MainLeftWidget)
        self.MainRightWidget = QtGui.QWidget(self.FontMainTab)
        self.MainRightWidget.setObjectName("MainRightWidget")
        self.MainRightLayout = QtGui.QVBoxLayout(self.MainRightWidget)
        self.MainRightLayout.setSpacing(8)
        self.MainRightLayout.setMargin(0)
        self.MainRightLayout.setObjectName("MainRightLayout")
        self.MainLocationGroupBox = QtGui.QGroupBox(self.MainRightWidget)
        self.MainLocationGroupBox.setObjectName("MainLocationGroupBox")
        self.MainLocationLayout = QtGui.QFormLayout(self.MainLocationGroupBox)
        self.MainLocationLayout.setMargin(8)
        self.MainLocationLayout.setSpacing(8)
        self.MainLocationLayout.setObjectName("MainLocationLayout")
        self.DefaultLocationLabel = QtGui.QLabel(self.MainLocationGroupBox)
        self.DefaultLocationLabel.setObjectName("DefaultLocationLabel")
        self.MainLocationLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.DefaultLocationLabel)
        self.FontMainDefaultCheckBox = QtGui.QCheckBox(self.MainLocationGroupBox)
        self.FontMainDefaultCheckBox.setTristate(False)
        self.FontMainDefaultCheckBox.setObjectName("FontMainDefaultCheckBox")
        self.MainLocationLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.FontMainDefaultCheckBox)
        self.FontMainXLabel = QtGui.QLabel(self.MainLocationGroupBox)
        self.FontMainXLabel.setObjectName("FontMainXLabel")
        self.MainLocationLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.FontMainXLabel)
        self.FontMainYLabel = QtGui.QLabel(self.MainLocationGroupBox)
        self.FontMainYLabel.setObjectName("FontMainYLabel")
        self.MainLocationLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.FontMainYLabel)
        self.FontMainWidthLabel = QtGui.QLabel(self.MainLocationGroupBox)
        self.FontMainWidthLabel.setObjectName("FontMainWidthLabel")
        self.MainLocationLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.FontMainWidthLabel)
        self.FontMainHeightLabel = QtGui.QLabel(self.MainLocationGroupBox)
        self.FontMainHeightLabel.setObjectName("FontMainHeightLabel")
        self.MainLocationLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.FontMainHeightLabel)
        self.FontMainXSpinBox = QtGui.QSpinBox(self.MainLocationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontMainXSpinBox.sizePolicy().hasHeightForWidth())
        self.FontMainXSpinBox.setSizePolicy(sizePolicy)
        self.FontMainXSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontMainXSpinBox.setProperty("value", QtCore.QVariant(0))
        self.FontMainXSpinBox.setMaximum(9999)
        self.FontMainXSpinBox.setObjectName("FontMainXSpinBox")
        self.MainLocationLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.FontMainXSpinBox)
        self.FontMainYSpinBox = QtGui.QSpinBox(self.MainLocationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontMainYSpinBox.sizePolicy().hasHeightForWidth())
        self.FontMainYSpinBox.setSizePolicy(sizePolicy)
        self.FontMainYSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontMainYSpinBox.setMaximum(9999)
        self.FontMainYSpinBox.setObjectName("FontMainYSpinBox")
        self.MainLocationLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.FontMainYSpinBox)
        self.FontMainWidthSpinBox = QtGui.QSpinBox(self.MainLocationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontMainWidthSpinBox.sizePolicy().hasHeightForWidth())
        self.FontMainWidthSpinBox.setSizePolicy(sizePolicy)
        self.FontMainWidthSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontMainWidthSpinBox.setMaximum(9999)
        self.FontMainWidthSpinBox.setObjectName("FontMainWidthSpinBox")
        self.MainLocationLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.FontMainWidthSpinBox)
        self.FontMainHeightSpinBox = QtGui.QSpinBox(self.MainLocationGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontMainHeightSpinBox.sizePolicy().hasHeightForWidth())
        self.FontMainHeightSpinBox.setSizePolicy(sizePolicy)
        self.FontMainHeightSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontMainHeightSpinBox.setMaximum(9999)
        self.FontMainHeightSpinBox.setObjectName("FontMainHeightSpinBox")
        self.MainLocationLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.FontMainHeightSpinBox)
        self.MainRightLayout.addWidget(self.MainLocationGroupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.MainRightLayout.addItem(spacerItem2)
        self.FontMainLayout.addWidget(self.MainRightWidget)
        self.ThemeTabWidget.addTab(self.FontMainTab, "")
        self.FontFooterTab = QtGui.QWidget()
        self.FontFooterTab.setObjectName("FontFooterTab")
        self.FontFooterLayout = QtGui.QHBoxLayout(self.FontFooterTab)
        self.FontFooterLayout.setSpacing(8)
        self.FontFooterLayout.setMargin(8)
        self.FontFooterLayout.setObjectName("FontFooterLayout")
        self.FooterLeftWidget = QtGui.QWidget(self.FontFooterTab)
        self.FooterLeftWidget.setObjectName("FooterLeftWidget")
        self.FooterLeftLayout = QtGui.QVBoxLayout(self.FooterLeftWidget)
        self.FooterLeftLayout.setSpacing(8)
        self.FooterLeftLayout.setMargin(0)
        self.FooterLeftLayout.setObjectName("FooterLeftLayout")
        self.FooterFontGroupBox = QtGui.QGroupBox(self.FooterLeftWidget)
        self.FooterFontGroupBox.setObjectName("FooterFontGroupBox")
        self.FooterFontLayout = QtGui.QFormLayout(self.FooterFontGroupBox)
        self.FooterFontLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.FooterFontLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FooterFontLayout.setMargin(8)
        self.FooterFontLayout.setSpacing(8)
        self.FooterFontLayout.setObjectName("FooterFontLayout")
        self.FontFooterLabel = QtGui.QLabel(self.FooterFontGroupBox)
        self.FontFooterLabel.setObjectName("FontFooterLabel")
        self.FooterFontLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.FontFooterLabel)
        self.FontFooterComboBox = QtGui.QFontComboBox(self.FooterFontGroupBox)
        self.FontFooterComboBox.setObjectName("FontFooterComboBox")
        self.FooterFontLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.FontFooterComboBox)
        self.FontFooterColorLabel = QtGui.QLabel(self.FooterFontGroupBox)
        self.FontFooterColorLabel.setObjectName("FontFooterColorLabel")
        self.FooterFontLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.FontFooterColorLabel)
        self.FontFooterColorPushButton = QtGui.QPushButton(self.FooterFontGroupBox)
        self.FontFooterColorPushButton.setObjectName("FontFooterColorPushButton")
        self.FooterFontLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.FontFooterColorPushButton)
        self.FontFooterSizeLabel = QtGui.QLabel(self.FooterFontGroupBox)
        self.FontFooterSizeLabel.setObjectName("FontFooterSizeLabel")
        self.FooterFontLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.FontFooterSizeLabel)
        self.FontFooterSizeSpinBox = QtGui.QSpinBox(self.FooterFontGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontFooterSizeSpinBox.sizePolicy().hasHeightForWidth())
        self.FontFooterSizeSpinBox.setSizePolicy(sizePolicy)
        self.FontFooterSizeSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.FontFooterSizeSpinBox.setProperty("value", QtCore.QVariant(10))
        self.FontFooterSizeSpinBox.setMaximum(999)
        self.FontFooterSizeSpinBox.setObjectName("FontFooterSizeSpinBox")
        self.FooterFontLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.FontFooterSizeSpinBox)
        self.FooterLeftLayout.addWidget(self.FooterFontGroupBox)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.FooterLeftLayout.addItem(spacerItem3)
        self.FontFooterLayout.addWidget(self.FooterLeftWidget)
        self.FooterRightWidget = QtGui.QWidget(self.FontFooterTab)
        self.FooterRightWidget.setObjectName("FooterRightWidget")
        self.FooterRightLayout = QtGui.QVBoxLayout(self.FooterRightWidget)
        self.FooterRightLayout.setSpacing(8)
        self.FooterRightLayout.setMargin(0)
        self.FooterRightLayout.setObjectName("FooterRightLayout")
        self.LocationFooterGroupBox = QtGui.QGroupBox(self.FooterRightWidget)
        self.LocationFooterGroupBox.setObjectName("LocationFooterGroupBox")
        self.LocationFooterLayout = QtGui.QFormLayout(self.LocationFooterGroupBox)
        self.LocationFooterLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.LocationFooterLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LocationFooterLayout.setMargin(8)
        self.LocationFooterLayout.setSpacing(8)
        self.LocationFooterLayout.setObjectName("LocationFooterLayout")
        self.FontFooterDefaultLabel = QtGui.QLabel(self.LocationFooterGroupBox)
        self.FontFooterDefaultLabel.setObjectName("FontFooterDefaultLabel")
        self.LocationFooterLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.FontFooterDefaultLabel)
        self.FontFooterDefaultCheckBox = QtGui.QCheckBox(self.LocationFooterGroupBox)
        self.FontFooterDefaultCheckBox.setTristate(False)
        self.FontFooterDefaultCheckBox.setObjectName("FontFooterDefaultCheckBox")
        self.LocationFooterLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.FontFooterDefaultCheckBox)
        self.FontFooterXLabel = QtGui.QLabel(self.LocationFooterGroupBox)
        self.FontFooterXLabel.setObjectName("FontFooterXLabel")
        self.LocationFooterLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.FontFooterXLabel)
        self.FontFooterYLabel = QtGui.QLabel(self.LocationFooterGroupBox)
        self.FontFooterYLabel.setObjectName("FontFooterYLabel")
        self.LocationFooterLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.FontFooterYLabel)
        self.FontFooterWidthLabel = QtGui.QLabel(self.LocationFooterGroupBox)
        self.FontFooterWidthLabel.setObjectName("FontFooterWidthLabel")
        self.LocationFooterLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.FontFooterWidthLabel)
        self.FontFooterHeightLabel = QtGui.QLabel(self.LocationFooterGroupBox)
        self.FontFooterHeightLabel.setObjectName("FontFooterHeightLabel")
        self.LocationFooterLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.FontFooterHeightLabel)
        self.FontFooterXSpinBox = QtGui.QSpinBox(self.LocationFooterGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontFooterXSpinBox.sizePolicy().hasHeightForWidth())
        self.FontFooterXSpinBox.setSizePolicy(sizePolicy)
        self.FontFooterXSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontFooterXSpinBox.setProperty("value", QtCore.QVariant(0))
        self.FontFooterXSpinBox.setMaximum(9999)
        self.FontFooterXSpinBox.setObjectName("FontFooterXSpinBox")
        self.LocationFooterLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.FontFooterXSpinBox)
        self.FontFooterYSpinBox = QtGui.QSpinBox(self.LocationFooterGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FontFooterYSpinBox.sizePolicy().hasHeightForWidth())
        self.FontFooterYSpinBox.setSizePolicy(sizePolicy)
        self.FontFooterYSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontFooterYSpinBox.setProperty("value", QtCore.QVariant(0))
        self.FontFooterYSpinBox.setMaximum(9999)
        self.FontFooterYSpinBox.setObjectName("FontFooterYSpinBox")
        self.LocationFooterLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.FontFooterYSpinBox)
        self.FontFooterWidthSpinBox = QtGui.QSpinBox(self.LocationFooterGroupBox)
        self.FontFooterWidthSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontFooterWidthSpinBox.setMaximum(9999)
        self.FontFooterWidthSpinBox.setObjectName("FontFooterWidthSpinBox")
        self.LocationFooterLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.FontFooterWidthSpinBox)
        self.FontFooterHeightSpinBox = QtGui.QSpinBox(self.LocationFooterGroupBox)
        self.FontFooterHeightSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.FontFooterHeightSpinBox.setMaximum(9999)
        self.FontFooterHeightSpinBox.setObjectName("FontFooterHeightSpinBox")
        self.LocationFooterLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.FontFooterHeightSpinBox)
        self.FooterRightLayout.addWidget(self.LocationFooterGroupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.FooterRightLayout.addItem(spacerItem4)
        self.FontFooterLayout.addWidget(self.FooterRightWidget)
        self.ThemeTabWidget.addTab(self.FontFooterTab, "")
        self.OtherOptionsTab = QtGui.QWidget()
        self.OtherOptionsTab.setObjectName("OtherOptionsTab")
        self.OtherOptionsLayout = QtGui.QHBoxLayout(self.OtherOptionsTab)
        self.OtherOptionsLayout.setSpacing(8)
        self.OtherOptionsLayout.setMargin(8)
        self.OtherOptionsLayout.setObjectName("OtherOptionsLayout")
        self.OptionsLeftWidget = QtGui.QWidget(self.OtherOptionsTab)
        self.OptionsLeftWidget.setObjectName("OptionsLeftWidget")
        self.OptionsLeftLayout = QtGui.QVBoxLayout(self.OptionsLeftWidget)
        self.OptionsLeftLayout.setSpacing(8)
        self.OptionsLeftLayout.setMargin(0)
        self.OptionsLeftLayout.setObjectName("OptionsLeftLayout")
        self.ShadowGroupBox = QtGui.QGroupBox(self.OptionsLeftWidget)
        self.ShadowGroupBox.setObjectName("ShadowGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.ShadowGroupBox)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setMargin(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OutlineWidget = QtGui.QWidget(self.ShadowGroupBox)
        self.OutlineWidget.setObjectName("OutlineWidget")
        self.OutlineLayout = QtGui.QFormLayout(self.OutlineWidget)
        self.OutlineLayout.setMargin(0)
        self.OutlineLayout.setSpacing(8)
        self.OutlineLayout.setObjectName("OutlineLayout")
        self.OutlineCheckBox = QtGui.QCheckBox(self.OutlineWidget)
        self.OutlineCheckBox.setObjectName("OutlineCheckBox")
        self.OutlineLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.OutlineCheckBox)
        self.OutlineColorLabel = QtGui.QLabel(self.OutlineWidget)
        self.OutlineColorLabel.setObjectName("OutlineColorLabel")
        self.OutlineLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.OutlineColorLabel)
        self.OutlineColorPushButton = QtGui.QPushButton(self.OutlineWidget)
        self.OutlineColorPushButton.setObjectName("OutlineColorPushButton")
        self.OutlineLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.OutlineColorPushButton)
        self.OutlineEnabledLabel = QtGui.QLabel(self.OutlineWidget)
        self.OutlineEnabledLabel.setObjectName("OutlineEnabledLabel")
        self.OutlineLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.OutlineEnabledLabel)
        self.verticalLayout.addWidget(self.OutlineWidget)
        self.ShadowWidget = QtGui.QWidget(self.ShadowGroupBox)
        self.ShadowWidget.setObjectName("ShadowWidget")
        self.ShadowLayout = QtGui.QFormLayout(self.ShadowWidget)
        self.ShadowLayout.setMargin(0)
        self.ShadowLayout.setSpacing(8)
        self.ShadowLayout.setObjectName("ShadowLayout")
        self.ShadowCheckBox = QtGui.QCheckBox(self.ShadowWidget)
        self.ShadowCheckBox.setObjectName("ShadowCheckBox")
        self.ShadowLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ShadowCheckBox)
        self.ShadowColorLabel = QtGui.QLabel(self.ShadowWidget)
        self.ShadowColorLabel.setObjectName("ShadowColorLabel")
        self.ShadowLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ShadowColorLabel)
        self.ShadowColorPushButton = QtGui.QPushButton(self.ShadowWidget)
        self.ShadowColorPushButton.setObjectName("ShadowColorPushButton")
        self.ShadowLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ShadowColorPushButton)
        self.ShadowEnabledLabel = QtGui.QLabel(self.ShadowWidget)
        self.ShadowEnabledLabel.setObjectName("ShadowEnabledLabel")
        self.ShadowLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.ShadowEnabledLabel)
        self.verticalLayout.addWidget(self.ShadowWidget)
        self.OptionsLeftLayout.addWidget(self.ShadowGroupBox)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.OptionsLeftLayout.addItem(spacerItem5)
        self.OtherOptionsLayout.addWidget(self.OptionsLeftWidget)
        self.OptionsRightWidget = QtGui.QWidget(self.OtherOptionsTab)
        self.OptionsRightWidget.setObjectName("OptionsRightWidget")
        self.OptionsRightLayout = QtGui.QVBoxLayout(self.OptionsRightWidget)
        self.OptionsRightLayout.setSpacing(8)
        self.OptionsRightLayout.setMargin(0)
        self.OptionsRightLayout.setObjectName("OptionsRightLayout")
        self.AlignmentGroupBox = QtGui.QGroupBox(self.OptionsRightWidget)
        self.AlignmentGroupBox.setObjectName("AlignmentGroupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.AlignmentGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.HorizontalLabel = QtGui.QLabel(self.AlignmentGroupBox)
        self.HorizontalLabel.setObjectName("HorizontalLabel")
        self.gridLayout_4.addWidget(self.HorizontalLabel, 0, 0, 1, 1)
        self.HorizontalComboBox = QtGui.QComboBox(self.AlignmentGroupBox)
        self.HorizontalComboBox.setObjectName("HorizontalComboBox")
        self.HorizontalComboBox.addItem(QtCore.QString())
        self.HorizontalComboBox.addItem(QtCore.QString())
        self.HorizontalComboBox.addItem(QtCore.QString())
        self.gridLayout_4.addWidget(self.HorizontalComboBox, 0, 1, 1, 1)
        self.VerticalLabel = QtGui.QLabel(self.AlignmentGroupBox)
        self.VerticalLabel.setObjectName("VerticalLabel")
        self.gridLayout_4.addWidget(self.VerticalLabel, 1, 0, 1, 1)
        self.VerticalComboBox = QtGui.QComboBox(self.AlignmentGroupBox)
        self.VerticalComboBox.setObjectName("VerticalComboBox")
        self.VerticalComboBox.addItem(QtCore.QString())
        self.VerticalComboBox.addItem(QtCore.QString())
        self.VerticalComboBox.addItem(QtCore.QString())
        self.gridLayout_4.addWidget(self.VerticalComboBox, 1, 1, 1, 1)
        self.OptionsRightLayout.addWidget(self.AlignmentGroupBox)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.OptionsRightLayout.addItem(spacerItem6)
        self.OtherOptionsLayout.addWidget(self.OptionsRightWidget)
        self.ThemeTabWidget.addTab(self.OtherOptionsTab, "")
        self.ContentLayout.addWidget(self.ThemeTabWidget)
        self.AmendThemeLayout.addWidget(self.ContentWidget)
        self.PreviewGroupBox = QtGui.QGroupBox(AmendThemeDialog)
        self.PreviewGroupBox.setObjectName("PreviewGroupBox")
        self.ThemePreviewLayout = QtGui.QHBoxLayout(self.PreviewGroupBox)
        self.ThemePreviewLayout.setSpacing(8)
        self.ThemePreviewLayout.setMargin(8)
        self.ThemePreviewLayout.setObjectName("ThemePreviewLayout")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ThemePreviewLayout.addItem(spacerItem7)
        self.ThemePreview = QtGui.QLabel(self.PreviewGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThemePreview.sizePolicy().hasHeightForWidth())
        self.ThemePreview.setSizePolicy(sizePolicy)
        self.ThemePreview.setMinimumSize(QtCore.QSize(300, 225))
        self.ThemePreview.setFrameShape(QtGui.QFrame.WinPanel)
        self.ThemePreview.setFrameShadow(QtGui.QFrame.Sunken)
        self.ThemePreview.setLineWidth(1)
        self.ThemePreview.setScaledContents(True)
        self.ThemePreview.setObjectName("ThemePreview")
        self.ThemePreviewLayout.addWidget(self.ThemePreview)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ThemePreviewLayout.addItem(spacerItem8)
        self.AmendThemeLayout.addWidget(self.PreviewGroupBox)
        self.ThemeButtonBox = QtGui.QDialogButtonBox(AmendThemeDialog)
        self.ThemeButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.ThemeButtonBox.setObjectName("ThemeButtonBox")
        self.AmendThemeLayout.addWidget(self.ThemeButtonBox)

        self.retranslateUi(AmendThemeDialog)
        self.ThemeTabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.ThemeButtonBox, QtCore.SIGNAL("accepted()"), AmendThemeDialog.accept)
        QtCore.QObject.connect(self.ThemeButtonBox, QtCore.SIGNAL("rejected()"), AmendThemeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AmendThemeDialog)
        AmendThemeDialog.setTabOrder(self.ThemeButtonBox, self.ThemeNameEdit)
        AmendThemeDialog.setTabOrder(self.ThemeNameEdit, self.ThemeTabWidget)
        AmendThemeDialog.setTabOrder(self.ThemeTabWidget, self.BackgroundComboBox)
        AmendThemeDialog.setTabOrder(self.BackgroundComboBox, self.BackgroundTypeComboBox)
        AmendThemeDialog.setTabOrder(self.BackgroundTypeComboBox, self.Color1PushButton)
        AmendThemeDialog.setTabOrder(self.Color1PushButton, self.Color2PushButton)
        AmendThemeDialog.setTabOrder(self.Color2PushButton, self.ImageLineEdit)
        AmendThemeDialog.setTabOrder(self.ImageLineEdit, self.ImageToolButton)
        AmendThemeDialog.setTabOrder(self.ImageToolButton, self.GradientComboBox)
        AmendThemeDialog.setTabOrder(self.GradientComboBox, self.FontMainComboBox)
        AmendThemeDialog.setTabOrder(self.FontMainComboBox, self.FontMainColorPushButton)
        AmendThemeDialog.setTabOrder(self.FontMainColorPushButton, self.FontMainSizeSpinBox)
        AmendThemeDialog.setTabOrder(self.FontMainSizeSpinBox, self.FontMainDefaultCheckBox)
        AmendThemeDialog.setTabOrder(self.FontMainDefaultCheckBox, self.FontMainXSpinBox)
        AmendThemeDialog.setTabOrder(self.FontMainXSpinBox, self.FontMainYSpinBox)
        AmendThemeDialog.setTabOrder(self.FontMainYSpinBox, self.FontMainWidthSpinBox)
        AmendThemeDialog.setTabOrder(self.FontMainWidthSpinBox, self.FontMainHeightSpinBox)
        AmendThemeDialog.setTabOrder(self.FontMainHeightSpinBox, self.FontFooterComboBox)
        AmendThemeDialog.setTabOrder(self.FontFooterComboBox, self.FontFooterColorPushButton)
        AmendThemeDialog.setTabOrder(self.FontFooterColorPushButton, self.FontFooterSizeSpinBox)
        AmendThemeDialog.setTabOrder(self.FontFooterSizeSpinBox, self.FontFooterDefaultCheckBox)
        AmendThemeDialog.setTabOrder(self.FontFooterDefaultCheckBox, self.FontFooterXSpinBox)
        AmendThemeDialog.setTabOrder(self.FontFooterXSpinBox, self.FontFooterYSpinBox)
        AmendThemeDialog.setTabOrder(self.FontFooterYSpinBox, self.FontFooterWidthSpinBox)
        AmendThemeDialog.setTabOrder(self.FontFooterWidthSpinBox, self.FontFooterHeightSpinBox)
        AmendThemeDialog.setTabOrder(self.FontFooterHeightSpinBox, self.OutlineCheckBox)
        AmendThemeDialog.setTabOrder(self.OutlineCheckBox, self.OutlineColorPushButton)
        AmendThemeDialog.setTabOrder(self.OutlineColorPushButton, self.ShadowCheckBox)
        AmendThemeDialog.setTabOrder(self.ShadowCheckBox, self.ShadowColorPushButton)
        AmendThemeDialog.setTabOrder(self.ShadowColorPushButton, self.HorizontalComboBox)
        AmendThemeDialog.setTabOrder(self.HorizontalComboBox, self.VerticalComboBox)

    def retranslateUi(self, AmendThemeDialog):
        AmendThemeDialog.setWindowTitle(QtGui.QApplication.translate("AmendThemeDialog", "Theme Maintance", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeNameLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Theme Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.BackgroundLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Background:", None, QtGui.QApplication.UnicodeUTF8))
        self.BackgroundComboBox.setItemText(0, QtGui.QApplication.translate("AmendThemeDialog", "Opaque", None, QtGui.QApplication.UnicodeUTF8))
        self.BackgroundComboBox.setItemText(1, QtGui.QApplication.translate("AmendThemeDialog", "Transparent", None, QtGui.QApplication.UnicodeUTF8))
        self.BackgroundTypeLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Background Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.BackgroundTypeComboBox.setItemText(0, QtGui.QApplication.translate("AmendThemeDialog", "Solid Color", None, QtGui.QApplication.UnicodeUTF8))
        self.BackgroundTypeComboBox.setItemText(1, QtGui.QApplication.translate("AmendThemeDialog", "Gradient", None, QtGui.QApplication.UnicodeUTF8))
        self.BackgroundTypeComboBox.setItemText(2, QtGui.QApplication.translate("AmendThemeDialog", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.Color1Label.setText(QtGui.QApplication.translate("AmendThemeDialog", "<Color1>", None, QtGui.QApplication.UnicodeUTF8))
        self.Color2Label.setText(QtGui.QApplication.translate("AmendThemeDialog", "<Color2>", None, QtGui.QApplication.UnicodeUTF8))
        self.ImageLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Image:", None, QtGui.QApplication.UnicodeUTF8))
        self.GradientLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Gradient :", None, QtGui.QApplication.UnicodeUTF8))
        self.GradientComboBox.setItemText(0, QtGui.QApplication.translate("AmendThemeDialog", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.GradientComboBox.setItemText(1, QtGui.QApplication.translate("AmendThemeDialog", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.GradientComboBox.setItemText(2, QtGui.QApplication.translate("AmendThemeDialog", "Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeTabWidget.setTabText(self.ThemeTabWidget.indexOf(self.BackgroundTab), QtGui.QApplication.translate("AmendThemeDialog", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainGroupBox.setTitle(QtGui.QApplication.translate("AmendThemeDialog", "Main Font", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainlabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainColorLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Font Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainSize.setText(QtGui.QApplication.translate("AmendThemeDialog", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainSizeSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.MainLocationGroupBox.setTitle(QtGui.QApplication.translate("AmendThemeDialog", "Display Location", None, QtGui.QApplication.UnicodeUTF8))
        self.DefaultLocationLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Use Default Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainXLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "X Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainYLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Y Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainWidthLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainHeightLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainXSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainYSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainWidthSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.FontMainHeightSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeTabWidget.setTabText(self.ThemeTabWidget.indexOf(self.FontMainTab), QtGui.QApplication.translate("AmendThemeDialog", "Font Main", None, QtGui.QApplication.UnicodeUTF8))
        self.FooterFontGroupBox.setTitle(QtGui.QApplication.translate("AmendThemeDialog", "Footer Font", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterColorLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Font Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterSizeLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterSizeSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationFooterGroupBox.setTitle(QtGui.QApplication.translate("AmendThemeDialog", "Display Location", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterDefaultLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Use Default Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterXLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "X Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterYLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Y Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterWidthLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterHeightLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterXSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterYSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterWidthSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.FontFooterHeightSpinBox.setSuffix(QtGui.QApplication.translate("AmendThemeDialog", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeTabWidget.setTabText(self.ThemeTabWidget.indexOf(self.FontFooterTab), QtGui.QApplication.translate("AmendThemeDialog", "Font Footer", None, QtGui.QApplication.UnicodeUTF8))
        self.ShadowGroupBox.setTitle(QtGui.QApplication.translate("AmendThemeDialog", "Shadow && Outline", None, QtGui.QApplication.UnicodeUTF8))
        self.OutlineColorLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Outline Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.OutlineEnabledLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Show Outline:", None, QtGui.QApplication.UnicodeUTF8))
        self.ShadowColorLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Shadow Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.ShadowEnabledLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Show Shadow:", None, QtGui.QApplication.UnicodeUTF8))
        self.AlignmentGroupBox.setTitle(QtGui.QApplication.translate("AmendThemeDialog", "Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.HorizontalLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Horizontal Align:", None, QtGui.QApplication.UnicodeUTF8))
        self.HorizontalComboBox.setItemText(0, QtGui.QApplication.translate("AmendThemeDialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.HorizontalComboBox.setItemText(1, QtGui.QApplication.translate("AmendThemeDialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.HorizontalComboBox.setItemText(2, QtGui.QApplication.translate("AmendThemeDialog", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.VerticalLabel.setText(QtGui.QApplication.translate("AmendThemeDialog", "Vertical Align:", None, QtGui.QApplication.UnicodeUTF8))
        self.VerticalComboBox.setItemText(0, QtGui.QApplication.translate("AmendThemeDialog", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.VerticalComboBox.setItemText(1, QtGui.QApplication.translate("AmendThemeDialog", "Middle", None, QtGui.QApplication.UnicodeUTF8))
        self.VerticalComboBox.setItemText(2, QtGui.QApplication.translate("AmendThemeDialog", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeTabWidget.setTabText(self.ThemeTabWidget.indexOf(self.OtherOptionsTab), QtGui.QApplication.translate("AmendThemeDialog", "Other Options", None, QtGui.QApplication.UnicodeUTF8))
        self.PreviewGroupBox.setTitle(QtGui.QApplication.translate("AmendThemeDialog", "Preview", None, QtGui.QApplication.UnicodeUTF8))

