# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firsttimewizard.ui'
#
# Created: Sun Feb 27 15:02:08 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FirstTimeWizard(object):
    def setupUi(self, FirstTimeWizard):
        FirstTimeWizard.setObjectName(_fromUtf8("FirstTimeWizard"))
        FirstTimeWizard.resize(550, 386)
        FirstTimeWizard.setModal(True)
        FirstTimeWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        FirstTimeWizard.setOptions(QtGui.QWizard.IndependentPages|QtGui.QWizard.NoBackButtonOnStartPage)
        self.welcomePage = QtGui.QWizardPage()
        self.welcomePage.setTitle(_fromUtf8(""))
        self.welcomePage.setSubTitle(_fromUtf8(""))
        self.welcomePage.setObjectName(_fromUtf8("welcomePage"))
        self.welcomeLayout = QtGui.QHBoxLayout(self.welcomePage)
        self.welcomeLayout.setSpacing(8)
        self.welcomeLayout.setMargin(0)
        self.welcomeLayout.setObjectName(_fromUtf8("welcomeLayout"))
        self.importBibleImage = QtGui.QLabel(self.welcomePage)
        self.importBibleImage.setMinimumSize(QtCore.QSize(163, 0))
        self.importBibleImage.setMaximumSize(QtCore.QSize(163, 16777215))
        self.importBibleImage.setLineWidth(0)
        self.importBibleImage.setText(_fromUtf8(""))
        self.importBibleImage.setPixmap(QtGui.QPixmap(_fromUtf8(":/wizards/wizard_importbible.bmp")))
        self.importBibleImage.setIndent(0)
        self.importBibleImage.setObjectName(_fromUtf8("importBibleImage"))
        self.welcomeLayout.addWidget(self.importBibleImage)
        self.welcomePageLayout = QtGui.QVBoxLayout()
        self.welcomePageLayout.setSpacing(8)
        self.welcomePageLayout.setObjectName(_fromUtf8("welcomePageLayout"))
        self.titleLabel = QtGui.QLabel(self.welcomePage)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.welcomePageLayout.addWidget(self.titleLabel)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.welcomePageLayout.addItem(spacerItem)
        self.informationLabel = QtGui.QLabel(self.welcomePage)
        self.informationLabel.setWordWrap(True)
        self.informationLabel.setMargin(10)
        self.informationLabel.setObjectName(_fromUtf8("informationLabel"))
        self.welcomePageLayout.addWidget(self.informationLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.welcomePageLayout.addItem(spacerItem1)
        self.welcomeLayout.addLayout(self.welcomePageLayout)
        FirstTimeWizard.addPage(self.welcomePage)
        self.PluginPagePage = QtGui.QWizardPage()
        self.PluginPagePage.setObjectName(_fromUtf8("PluginPagePage"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.PluginPagePage)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.songsCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.songsCheckBox.setChecked(True)
        self.songsCheckBox.setObjectName(_fromUtf8("songsCheckBox"))
        self.verticalLayout.addWidget(self.songsCheckBox)
        self.customCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.customCheckBox.setChecked(True)
        self.customCheckBox.setObjectName(_fromUtf8("customCheckBox"))
        self.verticalLayout.addWidget(self.customCheckBox)
        self.bibleCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.bibleCheckBox.setChecked(True)
        self.bibleCheckBox.setObjectName(_fromUtf8("bibleCheckBox"))
        self.verticalLayout.addWidget(self.bibleCheckBox)
        self.imageCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.imageCheckBox.setChecked(True)
        self.imageCheckBox.setObjectName(_fromUtf8("imageCheckBox"))
        self.verticalLayout.addWidget(self.imageCheckBox)
        self.presentationCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.presentationCheckBox.setChecked(True)
        self.presentationCheckBox.setObjectName(_fromUtf8("presentationCheckBox"))
        self.verticalLayout.addWidget(self.presentationCheckBox)
        self.mediaCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.mediaCheckBox.setChecked(True)
        self.mediaCheckBox.setObjectName(_fromUtf8("mediaCheckBox"))
        self.verticalLayout.addWidget(self.mediaCheckBox)
        self.remoteCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.remoteCheckBox.setObjectName(_fromUtf8("remoteCheckBox"))
        self.verticalLayout.addWidget(self.remoteCheckBox)
        self.songUsageCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.songUsageCheckBox.setChecked(True)
        self.songUsageCheckBox.setObjectName(_fromUtf8("songUsageCheckBox"))
        self.verticalLayout.addWidget(self.songUsageCheckBox)
        self.alertCheckBox = QtGui.QCheckBox(self.PluginPagePage)
        self.alertCheckBox.setChecked(True)
        self.alertCheckBox.setObjectName(_fromUtf8("alertCheckBox"))
        self.verticalLayout.addWidget(self.alertCheckBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        FirstTimeWizard.addPage(self.PluginPagePage)
        self.downloadDefaultsPage = QtGui.QWizardPage()
        self.downloadDefaultsPage.setObjectName(_fromUtf8("downloadDefaultsPage"))
        self.noInternetLabel = QtGui.QLabel(self.downloadDefaultsPage)
        self.noInternetLabel.setGeometry(QtCore.QRect(20, 20, 461, 17))
        self.noInternetLabel.setObjectName(_fromUtf8("noInternetLabel"))
        self.internetGroupBox = QtGui.QGroupBox(self.downloadDefaultsPage)
        self.internetGroupBox.setGeometry(QtCore.QRect(20, 10, 501, 271))
        self.internetGroupBox.setObjectName(_fromUtf8("internetGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.internetGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.selectionTreeWidget = QtGui.QTreeWidget(self.internetGroupBox)
        self.selectionTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.selectionTreeWidget.setProperty(_fromUtf8("showDropIndicator"), False)
        self.selectionTreeWidget.setAlternatingRowColors(True)
        #self.selectionTreeWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.selectionTreeWidget.setObjectName(_fromUtf8("selectionTreeWidget"))
        self.selectionTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.selectionTreeWidget.header().setVisible(False)
        self.verticalLayout_4.addWidget(self.selectionTreeWidget)
        FirstTimeWizard.addPage(self.downloadDefaultsPage)
        self.DefaultsPage = QtGui.QWizardPage()
        self.DefaultsPage.setObjectName(_fromUtf8("DefaultsPage"))
        self.layoutWidget = QtGui.QWidget(self.DefaultsPage)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 491, 113))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.displaySelectionLabel = QtGui.QLabel(self.layoutWidget)
        self.displaySelectionLabel.setObjectName(_fromUtf8("displaySelectionLabel"))
        self.gridLayout.addWidget(self.displaySelectionLabel, 0, 0, 1, 1)
        self.displaySelectionComboBox = QtGui.QComboBox(self.layoutWidget)
        self.displaySelectionComboBox.setEditable(False)
        self.displaySelectionComboBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.displaySelectionComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.displaySelectionComboBox.setObjectName(_fromUtf8("displaySelectionComboBox"))
        self.gridLayout.addWidget(self.displaySelectionComboBox, 0, 1, 1, 1)
        self.themeSelectionLabel = QtGui.QLabel(self.layoutWidget)
        self.themeSelectionLabel.setObjectName(_fromUtf8("themeSelectionLabel"))
        self.gridLayout.addWidget(self.themeSelectionLabel, 1, 0, 1, 1)
        self.themeSelectionComboBox = QtGui.QComboBox(self.layoutWidget)
        self.themeSelectionComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.themeSelectionComboBox.setObjectName(_fromUtf8("themeSelectionComboBox"))
        self.gridLayout.addWidget(self.themeSelectionComboBox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.DefaultsPage)
        self.label.setGeometry(QtCore.QRect(40, 190, 471, 17))
        self.label.setObjectName(_fromUtf8("label"))
        FirstTimeWizard.addPage(self.DefaultsPage)

        self.retranslateUi(FirstTimeWizard)
        QtCore.QMetaObject.connectSlotsByName(FirstTimeWizard)

    def retranslateUi(self, FirstTimeWizard):
        FirstTimeWizard.setWindowTitle(QtGui.QApplication.translate("FirstTimeWizard", "First Time Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("FirstTimeWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Welcome to the First Time Wizard</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.informationLabel.setText(QtGui.QApplication.translate("FirstTimeWizard", "This wizard will help you to configure OpenLP for initial use . Click the next button below to start the process of selection your initial options. ", None, QtGui.QApplication.UnicodeUTF8))
        self.PluginPagePage.setTitle(QtGui.QApplication.translate("FirstTimeWizard", "Activate required Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.PluginPagePage.setSubTitle(QtGui.QApplication.translate("FirstTimeWizard", "Select the Plugins you wish to use. ", None, QtGui.QApplication.UnicodeUTF8))
        self.songsCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Songs", None, QtGui.QApplication.UnicodeUTF8))
        self.customCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Custom Text", None, QtGui.QApplication.UnicodeUTF8))
        self.bibleCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Bible", None, QtGui.QApplication.UnicodeUTF8))
        self.imageCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.presentationCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Presentations", None, QtGui.QApplication.UnicodeUTF8))
        self.mediaCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Media (Audio and Video)", None, QtGui.QApplication.UnicodeUTF8))
        self.remoteCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Allow remote access", None, QtGui.QApplication.UnicodeUTF8))
        self.songUsageCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Monitor Song Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.alertCheckBox.setText(QtGui.QApplication.translate("FirstTimeWizard", "Allow Alerts", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadDefaultsPage.setTitle(QtGui.QApplication.translate("FirstTimeWizard", "Download Samples from OpenLP.org", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadDefaultsPage.setSubTitle(QtGui.QApplication.translate("FirstTimeWizard", "Select samples to downlaod and install for use.", None, QtGui.QApplication.UnicodeUTF8))
        self.noInternetLabel.setText(QtGui.QApplication.translate("FirstTimeWizard", "No Internet connection found so unable to download any default files.", None, QtGui.QApplication.UnicodeUTF8))
        self.internetGroupBox.setTitle(QtGui.QApplication.translate("FirstTimeWizard", "Download Example Files", None, QtGui.QApplication.UnicodeUTF8))
        self.DefaultsPage.setTitle(QtGui.QApplication.translate("FirstTimeWizard", "Default Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.DefaultsPage.setSubTitle(QtGui.QApplication.translate("FirstTimeWizard", "Set up default values to be used by OpenLP", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySelectionLabel.setText(QtGui.QApplication.translate("FirstTimeWizard", "Default output display", None, QtGui.QApplication.UnicodeUTF8))
        self.themeSelectionLabel.setText(QtGui.QApplication.translate("FirstTimeWizard", "Select the default Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FirstTimeWizard", "Press Finish to apply all you changes and start OpenLP", None, QtGui.QApplication.UnicodeUTF8))

