# -*- coding: utf-8 -*-
# vim: autoindent shiftwidth=4 expandtab textwidth=80 tabstop=4 softtabstop=4
"""
OpenLP - Open Source Lyrics Projection
Copyright (c) 2008 Raoul Snyman
Portions copyright (c) 2008 Martin Thompson, Tim Bentley,

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA
"""
import os
from time import sleep
from PyQt4 import QtCore, QtGui

from openlp.core.resources import *
from openlp.core.ui import AboutForm, AlertForm, SettingsDialog
from openlp.core.lib import Plugin, MediaManagerItem, SettingsTab
from openlp.core import PluginManager

class MainWindow(object):

    def __init__(self):
        self.main_window = QtGui.QMainWindow()
        self.about_form = AboutForm()
        self.alert_form = AlertForm()
        self.settings_form = SettingsDialog()
        pluginpath = os.path.split(os.path.abspath(__file__))[0]
        pluginpath = os.path.abspath(os.path.join(pluginpath, '..', '..','plugins'))
        self.plugin_manager = PluginManager(pluginpath)
        self.setupUi()

    def setupUi(self):
        self.main_window.setObjectName("main_window")
        self.main_window.resize(1087, 847)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_window.sizePolicy().hasHeightForWidth())
        self.main_window.setSizePolicy(sizePolicy)
        main_icon = QtGui.QIcon()
        main_icon.addPixmap(QtGui.QPixmap(":/icon/openlp.org-icon-32.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_window.setWindowIcon(main_icon)
        self.MainContent = QtGui.QWidget(self.main_window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainContent.sizePolicy().hasHeightForWidth())
        self.MainContent.setSizePolicy(sizePolicy)
        self.MainContent.setObjectName("MainContent")
        self.MainContentLayout = QtGui.QHBoxLayout(self.MainContent)
        self.MainContentLayout.setSpacing(0)
        self.MainContentLayout.setMargin(0)
        self.MainContentLayout.setObjectName("MainContentLayout")
        self.ControlSplitter = QtGui.QSplitter(self.MainContent)
        self.ControlSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.ControlSplitter.setObjectName("ControlSplitter")
        self.PreviewPane = QtGui.QWidget(self.ControlSplitter)
        self.PreviewPane.setObjectName("PreviewPane")
        self.PreviewPaneLayout = QtGui.QVBoxLayout(self.PreviewPane)
        self.PreviewPaneLayout.setSpacing(0)
        self.PreviewPaneLayout.setMargin(0)
        self.PreviewPaneLayout.setObjectName("PreviewPaneLayout")
        self.PreviewSplitter = QtGui.QSplitter(self.PreviewPane)
        self.PreviewSplitter.setOrientation(QtCore.Qt.Vertical)
        self.PreviewSplitter.setObjectName("PreviewSplitter")
        self.PreviewController = QtGui.QScrollArea(self.PreviewSplitter)
        self.PreviewController.setWidgetResizable(True)
        self.PreviewController.setObjectName("PreviewController")
        self.PreviewControllerContents = QtGui.QWidget(self.PreviewController)
        self.PreviewControllerContents.setGeometry(QtCore.QRect(0, 0, 228, 536))
        self.PreviewControllerContents.setObjectName("PreviewControllerContents")
        self.PreviewController.setWidget(self.PreviewControllerContents)
        self.PreviewScreen = QtGui.QGraphicsView(self.PreviewSplitter)
        self.PreviewScreen.setMaximumSize(QtCore.QSize(16777215, 250))
        self.PreviewScreen.setObjectName("PreviewScreen")
        self.PreviewPaneLayout.addWidget(self.PreviewSplitter)
        self.LivePane = QtGui.QWidget(self.ControlSplitter)
        self.LivePane.setObjectName("LivePane")
        self.LivePaneLayout = QtGui.QVBoxLayout(self.LivePane)
        self.LivePaneLayout.setSpacing(0)
        self.LivePaneLayout.setMargin(0)
        self.LivePaneLayout.setObjectName("LivePaneLayout")
        self.LiveSplitter = QtGui.QSplitter(self.LivePane)
        self.LiveSplitter.setOrientation(QtCore.Qt.Vertical)
        self.LiveSplitter.setObjectName("LiveSplitter")
        self.LiveController = QtGui.QScrollArea(self.LiveSplitter)
        self.LiveController.setWidgetResizable(True)
        self.LiveController.setObjectName("LiveController")
        self.LiveControllerContents = QtGui.QWidget(self.LiveController)
        self.LiveControllerContents.setGeometry(QtCore.QRect(0, 0, 227, 536))
        self.LiveControllerContents.setObjectName("LiveControllerContents")
        self.LiveController.setWidget(self.LiveControllerContents)
        self.LiveScreen = QtGui.QGraphicsView(self.LiveSplitter)
        self.LiveScreen.setMaximumSize(QtCore.QSize(16777215, 250))
        self.LiveScreen.setObjectName("LiveScreen")
        self.LivePaneLayout.addWidget(self.LiveSplitter)
        self.MainContentLayout.addWidget(self.ControlSplitter)
        self.main_window.setCentralWidget(self.MainContent)
        self.MenuBar = QtGui.QMenuBar(self.main_window)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 1087, 27))
        self.MenuBar.setObjectName("MenuBar")
        self.FileMenu = QtGui.QMenu(self.MenuBar)
        self.FileMenu.setObjectName("FileMenu")
        self.FileImportMenu = QtGui.QMenu(self.FileMenu)
        self.FileImportMenu.setObjectName("FileImportMenu")
        # Call the hook method to pull in import menus.
        self.plugin_manager.hook_import_menu(self.FileImportMenu)
        #
        self.FileExportMenu = QtGui.QMenu(self.FileMenu)
        self.FileExportMenu.setObjectName("FileExportMenu")
        # Call the hook method to pull in export menus.
        self.plugin_manager.hook_import_menu(self.FileExportMenu)
        #
        self.OptionsMenu = QtGui.QMenu(self.MenuBar)
        self.OptionsMenu.setObjectName("OptionsMenu")
        self.OptionsViewMenu = QtGui.QMenu(self.OptionsMenu)
        self.OptionsViewMenu.setObjectName("OptionsViewMenu")
        self.ViewModeMenu = QtGui.QMenu(self.OptionsViewMenu)
        self.ViewModeMenu.setObjectName("ViewModeMenu")
        self.OptionsLanguageMenu = QtGui.QMenu(self.OptionsMenu)
        self.OptionsLanguageMenu.setObjectName("OptionsLanguageMenu")
        self.ToolsMenu = QtGui.QMenu(self.MenuBar)
        self.ToolsMenu.setObjectName("ToolsMenu")
        self.HelpMenu = QtGui.QMenu(self.MenuBar)
        self.HelpMenu.setObjectName("HelpMenu")
        self.main_window.setMenuBar(self.MenuBar)
        self.StatusBar = QtGui.QStatusBar(self.main_window)
        self.StatusBar.setObjectName("StatusBar")
        self.main_window.setStatusBar(self.StatusBar)
        self.MediaManagerDock = QtGui.QDockWidget(self.main_window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MediaManagerDock.sizePolicy().hasHeightForWidth())
        self.MediaManagerDock.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/system/system_mediamanager.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MediaManagerDock.setWindowIcon(icon)
        self.MediaManagerDock.setFloating(False)
        self.MediaManagerDock.setObjectName("MediaManagerDock")
        self.MediaManagerDock.setMinimumWidth(250)
        self.MediaManagerContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MediaManagerContents.sizePolicy().hasHeightForWidth())
        self.MediaManagerContents.setSizePolicy(sizePolicy)
        self.MediaManagerContents.setObjectName("MediaManagerContents")
        self.MediaManagerLayout = QtGui.QHBoxLayout(self.MediaManagerContents)
        self.MediaManagerLayout.setContentsMargins(0, 2, 0, 0)
        self.MediaManagerLayout.setObjectName("MediaManagerLayout")
        self.MediaToolBox = QtGui.QToolBox(self.MediaManagerContents)
        #self.MediaToolBox.setTabSpacing(0)
        self.MediaToolBox.setObjectName("MediaToolBox")
        # This is where we will eventually get the Plugin Manager to pull in
        # the media manager items.
        self.plugin_manager.hook_media_manager(self.MediaToolBox)
        # End adding media manager items.
        self.MediaManagerLayout.addWidget(self.MediaToolBox)
        self.MediaManagerDock.setWidget(self.MediaManagerContents)
        self.main_window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.MediaManagerDock)
        self.ServiceManagerDock = QtGui.QDockWidget(self.main_window)
        ServiceManagerIcon = QtGui.QIcon()
        ServiceManagerIcon.addPixmap(QtGui.QPixmap(":/system/system_servicemanager.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ServiceManagerDock.setWindowIcon(ServiceManagerIcon)
        self.ServiceManagerDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.ServiceManagerDock.setObjectName("ServiceManagerDock")
        self.ServiceManagerContents = QtGui.QWidget()
        self.ServiceManagerContents.setObjectName("ServiceManagerContents")
        self.ServiceManagerLayout = QtGui.QVBoxLayout(self.ServiceManagerContents)
        self.ServiceManagerLayout.setSpacing(0)
        self.ServiceManagerLayout.setMargin(0)
        self.ServiceManagerLayout.setObjectName("ServiceManagerLayout")
        self.ServiceToolbar = QtGui.QToolBar(self.ServiceManagerContents)
        self.ServiceToolbar.setObjectName("ServiceToolbar")
        MoveTopIcon = QtGui.QIcon()
        MoveTopIcon.addPixmap(QtGui.QPixmap(":/services/service_top.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MoveTopButton = self.ServiceToolbar.addAction(MoveTopIcon, 'Move to top')
        MoveUpIcon = QtGui.QIcon()
        MoveUpIcon.addPixmap(QtGui.QPixmap(":/services/service_up.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MoveUpButton = self.ServiceToolbar.addAction(MoveUpIcon, 'Move up')
        MoveDownIcon = QtGui.QIcon()
        MoveDownIcon.addPixmap(QtGui.QPixmap(":/services/service_down.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MoveDownButton = self.ServiceToolbar.addAction(MoveDownIcon, 'Move down')
        MoveBottomIcon = QtGui.QIcon()
        MoveBottomIcon.addPixmap(QtGui.QPixmap(":/services/service_bottom.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MoveBottomButton = self.ServiceToolbar.addAction(MoveBottomIcon, 'Move to bottom')
        self.ServiceToolbar.addSeparator()
        NewServiceIcon = QtGui.QIcon()
        NewServiceIcon.addPixmap(QtGui.QPixmap(":/services/service_new.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ServiceNewItem = self.ServiceToolbar.addAction(NewServiceIcon, 'New service')
        OpenServiceIcon = QtGui.QIcon()
        OpenServiceIcon.addPixmap(QtGui.QPixmap(":/services/service_open.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ServiceOpenItem = self.ServiceToolbar.addAction(OpenServiceIcon, 'Open service')
        SaveServiceIcon = QtGui.QIcon()
        SaveServiceIcon.addPixmap(QtGui.QPixmap(":/services/service_save.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ServiceSaveItem = self.ServiceToolbar.addAction(SaveServiceIcon, 'Save service')
        self.ServiceToolbar.addSeparator()
        self.ServiceThemeComboBox = QtGui.QComboBox(self.ServiceToolbar)
        self.ServiceThemeComboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.ServiceThemeComboBox.setObjectName("ServiceThemeComboBox")
        self.ServiceThemeComboBox.addItem(QtCore.QString())
        self.ServiceThemeComboBox.addItem(QtCore.QString())
        self.ServiceThemeComboBox.addItem(QtCore.QString())
        self.ServiceThemeWidget = QtGui.QWidgetAction(self.ServiceToolbar)
        self.ServiceThemeWidget.setDefaultWidget(self.ServiceThemeComboBox)
        self.ServiceToolbar.addAction(self.ServiceThemeWidget)
        self.ServiceManagerLayout.addWidget(self.ServiceToolbar)
        self.ServiceListView = QtGui.QListView(self.ServiceManagerContents)
        self.ServiceListView.setObjectName("ServiceListView")
        self.ServiceManagerLayout.addWidget(self.ServiceListView)
        self.ServiceManagerDock.setWidget(self.ServiceManagerContents)
        self.main_window.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.ServiceManagerDock)
        self.ThemeManagerDock = QtGui.QDockWidget(self.main_window)
        ThemeManagerIcon = QtGui.QIcon()
        ThemeManagerIcon.addPixmap(QtGui.QPixmap(":/system/system_thememanager.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ThemeManagerDock.setWindowIcon(ThemeManagerIcon)
        self.ThemeManagerDock.setFloating(False)
        self.ThemeManagerDock.setObjectName("ThemeManagerDock")
        self.ThemeManagerContents = QtGui.QWidget()
        self.ThemeManagerContents.setObjectName("ThemeManagerContents")
        self.ThemeManagerLayout = QtGui.QVBoxLayout(self.ThemeManagerContents)
        self.ThemeManagerLayout.setSpacing(0)
        self.ThemeManagerLayout.setMargin(0)
        self.ThemeManagerLayout.setObjectName("ThemeManagerLayout")
        self.ThemeManagerToolbar = QtGui.QToolBar(self.ThemeManagerContents)
        self.ThemeManagerToolbar.setObjectName("ThemeManagerToolbar")
        NewThemeIcon = QtGui.QIcon()
        NewThemeIcon.addPixmap(QtGui.QPixmap(":/themes/theme_new.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ThemeNewItem = self.ThemeManagerToolbar.addAction(NewThemeIcon, 'New theme')
        EditThemeIcon = QtGui.QIcon()
        EditThemeIcon.addPixmap(QtGui.QPixmap(":/themes/theme_edit.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ThemeEditItem = self.ThemeManagerToolbar.addAction(EditThemeIcon, 'Edit theme')
        DeleteThemeIcon = QtGui.QIcon()
        DeleteThemeIcon.addPixmap(QtGui.QPixmap(":/themes/theme_delete.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ThemeDeleteButton = self.ThemeManagerToolbar.addAction(DeleteThemeIcon, 'Delete theme')
        self.ThemeManagerToolbar.addSeparator()
        ImportThemeIcon = QtGui.QIcon()
        ImportThemeIcon.addPixmap(QtGui.QPixmap(":/themes/theme_import.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ThemeImportButton = self.ThemeManagerToolbar.addAction(ImportThemeIcon, 'Import theme')
        ExportThemeIcon = QtGui.QIcon()
        ExportThemeIcon.addPixmap(QtGui.QPixmap(":/themes/theme_export.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ThemeExportButton = self.ThemeManagerToolbar.addAction(ExportThemeIcon, 'Export theme')
        self.ThemeManagerLayout.addWidget(self.ThemeManagerToolbar)
        self.ThemeManagerListView = QtGui.QListView(self.ThemeManagerContents)
        self.ThemeManagerListView.setObjectName("ThemeManagerListView")
        self.ThemeManagerLayout.addWidget(self.ThemeManagerListView)
        self.ThemeManagerDock.setWidget(self.ThemeManagerContents)
        self.main_window.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.ThemeManagerDock)
        self.FileNewItem = QtGui.QAction(self.main_window)
        self.FileNewItem.setIcon(NewServiceIcon)
        self.FileNewItem.setObjectName("FileNewItem")
        self.FileOpenItem = QtGui.QAction(self.main_window)
        self.FileOpenItem.setIcon(OpenServiceIcon)
        self.FileOpenItem.setObjectName("FileOpenItem")
        self.FileSaveItem = QtGui.QAction(self.main_window)
        self.FileSaveItem.setIcon(SaveServiceIcon)
        self.FileSaveItem.setObjectName("FileSaveItem")
        self.FileSaveAsItem = QtGui.QAction(self.main_window)
        self.FileSaveAsItem.setObjectName("FileSaveAsItem")
        self.FileExitItem = QtGui.QAction(self.main_window)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/system/system_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FileExitItem.setIcon(icon34)
        self.FileExitItem.setObjectName("FileExitItem")
        self.ImportThemeItem = QtGui.QAction(self.main_window)
        self.ImportThemeItem.setObjectName("ImportThemeItem")
        self.ImportLanguageItem = QtGui.QAction(self.main_window)
        self.ImportLanguageItem.setObjectName("ImportLanguageItem")
        self.ExportThemeItem = QtGui.QAction(self.main_window)
        self.ExportThemeItem.setObjectName("ExportThemeItem")
        self.ExportLanguageItem = QtGui.QAction(self.main_window)
        self.ExportLanguageItem.setObjectName("ExportLanguageItem")
        self.actionLook_Feel = QtGui.QAction(self.main_window)
        self.actionLook_Feel.setObjectName("actionLook_Feel")
        self.OptionsSettingsItem = QtGui.QAction(self.main_window)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/system/system_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OptionsSettingsItem.setIcon(icon35)
        self.OptionsSettingsItem.setObjectName("OptionsSettingsItem")
        self.ViewMediaManagerItem = QtGui.QAction(self.main_window)
        self.ViewMediaManagerItem.setCheckable(True)
        self.ViewMediaManagerItem.setChecked(True)
        self.ViewMediaManagerItem.setIcon(icon)
        self.ViewMediaManagerItem.setObjectName("ViewMediaManagerItem")
        self.ViewThemeManagerItem = QtGui.QAction(self.main_window)
        self.ViewThemeManagerItem.setCheckable(True)
        self.ViewThemeManagerItem.setChecked(True)
        self.ViewThemeManagerItem.setIcon(ThemeManagerIcon)
        self.ViewThemeManagerItem.setObjectName("ViewThemeManagerItem")
        self.ViewServiceManagerItem = QtGui.QAction(self.main_window)
        self.ViewServiceManagerItem.setCheckable(True)
        self.ViewServiceManagerItem.setChecked(True)
        self.ViewServiceManagerItem.setIcon(ServiceManagerIcon)
        self.ViewServiceManagerItem.setObjectName("ViewServiceManagerItem")
        self.ToolsAlertItem = QtGui.QAction(self.main_window)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/tools/tools_alert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToolsAlertItem.setIcon(icon36)
        self.ToolsAlertItem.setObjectName("ToolsAlertItem")
        self.HelpDocumentationItem = QtGui.QAction(self.main_window)
        self.HelpDocumentationItem.setObjectName("HelpDocumentationItem")
        self.HelpAboutItem = QtGui.QAction(self.main_window)
        self.HelpAboutItem.setObjectName("HelpAboutItem")
        self.HelpOnlineHelpItem = QtGui.QAction(self.main_window)
        self.HelpOnlineHelpItem.setObjectName("HelpOnlineHelpItem")
        self.HelpWebSiteItem = QtGui.QAction(self.main_window)
        self.HelpWebSiteItem.setObjectName("HelpWebSiteItem")
        self.LanguageTranslateItem = QtGui.QAction(self.main_window)
        self.LanguageTranslateItem.setObjectName("LanguageTranslateItem")
        self.LanguageEnglishItem = QtGui.QAction(self.main_window)
        self.LanguageEnglishItem.setObjectName("LanguageEnglishItem")
        self.ToolsAddToolItem = QtGui.QAction(self.main_window)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/tools/tools_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToolsAddToolItem.setIcon(icon37)
        self.ToolsAddToolItem.setObjectName("ToolsAddToolItem")
        self.action_Preview_Pane = QtGui.QAction(self.main_window)
        self.action_Preview_Pane.setCheckable(True)
        self.action_Preview_Pane.setChecked(True)
        self.action_Preview_Pane.setObjectName("action_Preview_Pane")
        self.ModeLiveItem = QtGui.QAction(self.main_window)
        self.ModeLiveItem.setObjectName("ModeLiveItem")
        self.FileImportMenu.addAction(self.ImportThemeItem)
        self.FileImportMenu.addAction(self.ImportLanguageItem)
        self.FileExportMenu.addAction(self.ExportThemeItem)
        self.FileExportMenu.addAction(self.ExportLanguageItem)
        self.FileMenu.addAction(self.FileNewItem)
        self.FileMenu.addAction(self.FileOpenItem)
        self.FileMenu.addAction(self.FileSaveItem)
        self.FileMenu.addAction(self.FileSaveAsItem)
        self.FileMenu.addSeparator()
        self.FileMenu.addAction(self.FileImportMenu.menuAction())
        self.FileMenu.addAction(self.FileExportMenu.menuAction())
        self.FileMenu.addSeparator()
        self.FileMenu.addAction(self.FileExitItem)
        self.ViewModeMenu.addAction(self.ModeLiveItem)
        self.OptionsViewMenu.addAction(self.ViewModeMenu.menuAction())
        self.OptionsViewMenu.addSeparator()
        self.OptionsViewMenu.addAction(self.ViewMediaManagerItem)
        self.OptionsViewMenu.addAction(self.ViewServiceManagerItem)
        self.OptionsViewMenu.addAction(self.ViewThemeManagerItem)
        self.OptionsViewMenu.addSeparator()
        self.OptionsViewMenu.addAction(self.action_Preview_Pane)
        self.OptionsLanguageMenu.addAction(self.LanguageEnglishItem)
        self.OptionsLanguageMenu.addSeparator()
        self.OptionsLanguageMenu.addAction(self.LanguageTranslateItem)
        self.OptionsMenu.addAction(self.OptionsLanguageMenu.menuAction())
        self.OptionsMenu.addAction(self.OptionsViewMenu.menuAction())
        self.OptionsMenu.addSeparator()
        self.OptionsMenu.addAction(self.OptionsSettingsItem)
        self.ToolsMenu.addAction(self.ToolsAlertItem)
        self.ToolsMenu.addSeparator()
        self.ToolsMenu.addAction(self.ToolsAddToolItem)
        self.HelpMenu.addAction(self.HelpDocumentationItem)
        self.HelpMenu.addAction(self.HelpOnlineHelpItem)
        self.HelpMenu.addSeparator()
        self.HelpMenu.addAction(self.HelpWebSiteItem)
        self.HelpMenu.addAction(self.HelpAboutItem)
        self.MenuBar.addAction(self.FileMenu.menuAction())
        self.MenuBar.addAction(self.OptionsMenu.menuAction())
        self.MenuBar.addAction(self.ToolsMenu.menuAction())
        self.MenuBar.addAction(self.HelpMenu.menuAction())

        self.retranslateUi()
        self.MediaToolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.FileExitItem, QtCore.SIGNAL("triggered()"), self.main_window.close)
        QtCore.QObject.connect(self.ViewMediaManagerItem, QtCore.SIGNAL("triggered(bool)"), self.MediaManagerDock.setVisible)
        QtCore.QObject.connect(self.ViewServiceManagerItem, QtCore.SIGNAL("triggered(bool)"), self.ServiceManagerDock.setVisible)
        QtCore.QObject.connect(self.ViewThemeManagerItem, QtCore.SIGNAL("triggered(bool)"), self.ThemeManagerDock.setVisible)
        QtCore.QObject.connect(self.action_Preview_Pane, QtCore.SIGNAL("toggled(bool)"), self.PreviewPane.setVisible)
        QtCore.QObject.connect(self.MediaManagerDock, QtCore.SIGNAL("visibilityChanged(bool)"), self.ViewMediaManagerItem.setChecked)
        QtCore.QObject.connect(self.ServiceManagerDock, QtCore.SIGNAL("visibilityChanged(bool)"), self.ViewServiceManagerItem.setChecked)
        QtCore.QObject.connect(self.ThemeManagerDock, QtCore.SIGNAL("visibilityChanged(bool)"), self.ViewThemeManagerItem.setChecked)
        QtCore.QMetaObject.connectSlotsByName(self.main_window)
        QtCore.QObject.connect(self.HelpAboutItem, QtCore.SIGNAL("triggered()"), self.onHelpAboutItemClicked)
        QtCore.QObject.connect(self.ToolsAlertItem, QtCore.SIGNAL("triggered()"), self.onToolsAlertItemClicked)
        QtCore.QObject.connect(self.OptionsSettingsItem, QtCore.SIGNAL("triggered()"), self.onOptionsSettingsItemClicked)

    def retranslateUi(self):
        self.main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "openlp.org 2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.FileMenu.setTitle(QtGui.QApplication.translate("main_window", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.FileImportMenu.setTitle(QtGui.QApplication.translate("main_window", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.FileExportMenu.setTitle(QtGui.QApplication.translate("main_window", "&Export", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionsMenu.setTitle(QtGui.QApplication.translate("main_window", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionsViewMenu.setTitle(QtGui.QApplication.translate("main_window", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewModeMenu.setTitle(QtGui.QApplication.translate("main_window", "M&ode", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionsLanguageMenu.setTitle(QtGui.QApplication.translate("main_window", "&Language", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsMenu.setTitle(QtGui.QApplication.translate("main_window", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpMenu.setTitle(QtGui.QApplication.translate("main_window", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.MediaManagerDock.setWindowTitle(QtGui.QApplication.translate("main_window", "Media Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceManagerDock.setWindowTitle(QtGui.QApplication.translate("main_window", "Service Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.MoveTopButton.setText(QtGui.QApplication.translate("main_window", "Move To Top", None, QtGui.QApplication.UnicodeUTF8))
        self.MoveUpButton.setText(QtGui.QApplication.translate("main_window", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.MoveDownButton.setText(QtGui.QApplication.translate("main_window", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.MoveBottomButton.setText(QtGui.QApplication.translate("main_window", "Move To Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceNewItem.setText(QtGui.QApplication.translate("main_window", "New Service", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceOpenItem.setText(QtGui.QApplication.translate("main_window", "Open Service", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceSaveItem.setText(QtGui.QApplication.translate("main_window", "Save Service", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceThemeComboBox.setItemText(0, QtGui.QApplication.translate("main_window", "African Sunset", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceThemeComboBox.setItemText(1, QtGui.QApplication.translate("main_window", "Snowy Mountains", None, QtGui.QApplication.UnicodeUTF8))
        self.ServiceThemeComboBox.setItemText(2, QtGui.QApplication.translate("main_window", "Wilderness", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeManagerDock.setWindowTitle(QtGui.QApplication.translate("main_window", "Theme Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeNewItem.setText(QtGui.QApplication.translate("main_window", "New Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeEditItem.setText(QtGui.QApplication.translate("main_window", "Edit Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeDeleteButton.setText(QtGui.QApplication.translate("main_window", "Delete Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeImportButton.setText(QtGui.QApplication.translate("main_window", "Import Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeExportButton.setText(QtGui.QApplication.translate("main_window", "Export Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.FileNewItem.setText(QtGui.QApplication.translate("main_window", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.FileNewItem.setToolTip(QtGui.QApplication.translate("main_window", "New Service", None, QtGui.QApplication.UnicodeUTF8))
        self.FileNewItem.setStatusTip(QtGui.QApplication.translate("main_window", "Create a new Service", None, QtGui.QApplication.UnicodeUTF8))
        self.FileNewItem.setShortcut(QtGui.QApplication.translate("main_window", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.FileOpenItem.setText(QtGui.QApplication.translate("main_window", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.FileOpenItem.setToolTip(QtGui.QApplication.translate("main_window", "Open Service", None, QtGui.QApplication.UnicodeUTF8))
        self.FileOpenItem.setStatusTip(QtGui.QApplication.translate("main_window", "Open an existing service", None, QtGui.QApplication.UnicodeUTF8))
        self.FileOpenItem.setShortcut(QtGui.QApplication.translate("main_window", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveItem.setText(QtGui.QApplication.translate("main_window", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveItem.setToolTip(QtGui.QApplication.translate("main_window", "Save Service", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveItem.setStatusTip(QtGui.QApplication.translate("main_window", "Save the current service to disk", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveItem.setShortcut(QtGui.QApplication.translate("main_window", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveAsItem.setText(QtGui.QApplication.translate("main_window", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveAsItem.setToolTip(QtGui.QApplication.translate("main_window", "Save Service As", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveAsItem.setStatusTip(QtGui.QApplication.translate("main_window", "Save the current service under a new name", None, QtGui.QApplication.UnicodeUTF8))
        self.FileSaveAsItem.setShortcut(QtGui.QApplication.translate("main_window", "F12", None, QtGui.QApplication.UnicodeUTF8))
        self.FileExitItem.setText(QtGui.QApplication.translate("main_window", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.FileExitItem.setStatusTip(QtGui.QApplication.translate("main_window", "Quit OpenLP 2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.FileExitItem.setShortcut(QtGui.QApplication.translate("main_window", "Alt+F4", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportThemeItem.setText(QtGui.QApplication.translate("main_window", "&Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.ImportLanguageItem.setText(QtGui.QApplication.translate("main_window", "&Language", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportThemeItem.setText(QtGui.QApplication.translate("main_window", "&Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportLanguageItem.setText(QtGui.QApplication.translate("main_window", "&Language", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLook_Feel.setText(QtGui.QApplication.translate("main_window", "Look && &Feel", None, QtGui.QApplication.UnicodeUTF8))
        self.OptionsSettingsItem.setText(QtGui.QApplication.translate("main_window", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewMediaManagerItem.setText(QtGui.QApplication.translate("main_window", "&Media Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewMediaManagerItem.setToolTip(QtGui.QApplication.translate("main_window", "Toggle Media Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewMediaManagerItem.setStatusTip(QtGui.QApplication.translate("main_window", "Toggle the visibility of the Media Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewMediaManagerItem.setShortcut(QtGui.QApplication.translate("main_window", "F8", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewThemeManagerItem.setText(QtGui.QApplication.translate("main_window", "&Theme Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewThemeManagerItem.setToolTip(QtGui.QApplication.translate("main_window", "Toggle Theme Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewThemeManagerItem.setStatusTip(QtGui.QApplication.translate("main_window", "Toggle the visibility of the Theme Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewThemeManagerItem.setShortcut(QtGui.QApplication.translate("main_window", "F10", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewServiceManagerItem.setText(QtGui.QApplication.translate("main_window", "&Service Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewServiceManagerItem.setToolTip(QtGui.QApplication.translate("main_window", "Toggle Service Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewServiceManagerItem.setStatusTip(QtGui.QApplication.translate("main_window", "Toggle the visibility of the Service Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.ViewServiceManagerItem.setShortcut(QtGui.QApplication.translate("main_window", "F9", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsAlertItem.setText(QtGui.QApplication.translate("main_window", "&Alert", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsAlertItem.setStatusTip(QtGui.QApplication.translate("main_window", "Show an alert message", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsAlertItem.setShortcut(QtGui.QApplication.translate("main_window", "F7", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpDocumentationItem.setText(QtGui.QApplication.translate("main_window", "&User Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpAboutItem.setText(QtGui.QApplication.translate("main_window", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpAboutItem.setStatusTip(QtGui.QApplication.translate("main_window", "More information about OpenLP", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpAboutItem.setShortcut(QtGui.QApplication.translate("main_window", "Ctrl+F1", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpOnlineHelpItem.setText(QtGui.QApplication.translate("main_window", "&Online Help", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpWebSiteItem.setText(QtGui.QApplication.translate("main_window", "&Web Site", None, QtGui.QApplication.UnicodeUTF8))
        self.LanguageTranslateItem.setText(QtGui.QApplication.translate("main_window", "&Translate", None, QtGui.QApplication.UnicodeUTF8))
        self.LanguageTranslateItem.setStatusTip(QtGui.QApplication.translate("main_window", "Translate the interface to your language", None, QtGui.QApplication.UnicodeUTF8))
        self.LanguageEnglishItem.setText(QtGui.QApplication.translate("main_window", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.LanguageEnglishItem.setStatusTip(QtGui.QApplication.translate("main_window", "Set the interface language to English", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsAddToolItem.setText(QtGui.QApplication.translate("main_window", "&Add Tool...", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsAddToolItem.setStatusTip(QtGui.QApplication.translate("main_window", "Add an application to the list of tools", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Preview_Pane.setText(QtGui.QApplication.translate("main_window", "&Preview Pane", None, QtGui.QApplication.UnicodeUTF8))
        self.ModeLiveItem.setText(QtGui.QApplication.translate("main_window", "&Live", None, QtGui.QApplication.UnicodeUTF8))

    def show(self):
        sleep(2)
        self.main_window.showMaximized()

    def onHelpAboutItemClicked(self):
        self.about_form.show()

    def onToolsAlertItemClicked(self):
        self.alert_form.show()

    def onOptionsSettingsItemClicked(self):
        self.settings_form.show()

#        self.VersePage = QtGui.QWidget()
#        self.VersePage.setGeometry(QtCore.QRect(0, 0, 267, 609))
#        self.VersePage.setObjectName("VersePage")
#        self.VersesPageLayout = QtGui.QVBoxLayout(self.VersePage)
#        self.VersesPageLayout.setSpacing(0)
#        self.VersesPageLayout.setMargin(0)
#        self.VersesPageLayout.setObjectName("VersesPageLayout")
#        self.VerseToolbar = QtGui.QWidget(self.VersePage)
#        self.VerseToolbar.setObjectName("VerseToolbar")
#        self.VerseToolbarLayout = QtGui.QHBoxLayout(self.VerseToolbar)
#        self.VerseToolbarLayout.setSpacing(0)
#        self.VerseToolbarLayout.setMargin(0)
#        self.VerseToolbarLayout.setObjectName("VerseToolbarLayout")
#        self.VersePreviewItem = QtGui.QToolButton(self.VerseToolbar)
#        self.VersePreviewItem.setIcon(icon4)
#        self.VersePreviewItem.setIconSize(QtCore.QSize(20, 20))
#        self.VersePreviewItem.setAutoRaise(True)
#        self.VersePreviewItem.setObjectName("VersePreviewItem")
#        self.VerseToolbarLayout.addWidget(self.VersePreviewItem)
#        self.VerseLiveItem = QtGui.QToolButton(self.VerseToolbar)
#        self.VerseLiveItem.setIcon(icon5)
#        self.VerseLiveItem.setIconSize(QtCore.QSize(20, 20))
#        self.VerseLiveItem.setAutoRaise(True)
#        self.VerseLiveItem.setObjectName("VerseLiveItem")
#        self.VerseToolbarLayout.addWidget(self.VerseLiveItem)
#        self.VerseAddItem = QtGui.QToolButton(self.VerseToolbar)
#        self.VerseAddItem.setIcon(icon6)
#        self.VerseAddItem.setIconSize(QtCore.QSize(20, 20))
#        self.VerseAddItem.setAutoRaise(True)
#        self.VerseAddItem.setObjectName("VerseAddItem")
#        self.VerseToolbarLayout.addWidget(self.VerseAddItem)
#        spacerItem1 = QtGui.QSpacerItem(166, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
#        self.VerseToolbarLayout.addItem(spacerItem1)
#        self.VersesPageLayout.addWidget(self.VerseToolbar)
#        self.line = QtGui.QFrame(self.VersePage)
#        self.line.setFrameShape(QtGui.QFrame.HLine)
#        self.line.setFrameShadow(QtGui.QFrame.Sunken)
#        self.line.setObjectName("line")
#        self.VersesPageLayout.addWidget(self.line)
#        self.VerseSearchWidget = QtGui.QWidget(self.VersePage)
#        self.VerseSearchWidget.setObjectName("VerseSearchWidget")
#        self.VerseSearchLayout = QtGui.QGridLayout(self.VerseSearchWidget)
#        self.VerseSearchLayout.setMargin(8)
#        self.VerseSearchLayout.setSpacing(8)
#        self.VerseSearchLayout.setObjectName("VerseSearchLayout")
#        self.label = QtGui.QLabel(self.VerseSearchWidget)
#        self.label.setObjectName("label")
#        self.VerseSearchLayout.addWidget(self.label, 0, 0, 1, 1)
#        self.comboBox = QtGui.QComboBox(self.VerseSearchWidget)
#        self.comboBox.setObjectName("comboBox")
#        self.VerseSearchLayout.addWidget(self.comboBox, 0, 1, 1, 1)
#        self.label_2 = QtGui.QLabel(self.VerseSearchWidget)
#        self.label_2.setObjectName("label_2")
#        self.VerseSearchLayout.addWidget(self.label_2, 1, 0, 1, 1)
#        self.lineEdit = QtGui.QLineEdit(self.VerseSearchWidget)
#        self.lineEdit.setObjectName("lineEdit")
#        self.VerseSearchLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
#        self.widget = QtGui.QWidget(self.VerseSearchWidget)
#        self.widget.setObjectName("widget")
#        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
#        self.horizontalLayout.setSpacing(0)
#        self.horizontalLayout.setMargin(0)
#        self.horizontalLayout.setObjectName("horizontalLayout")
#        spacerItem2 = QtGui.QSpacerItem(83, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
#        self.horizontalLayout.addItem(spacerItem2)
#        self.pushButton = QtGui.QPushButton(self.widget)
#        self.pushButton.setObjectName("pushButton")
#        self.horizontalLayout.addWidget(self.pushButton)
#        self.VerseSearchLayout.addWidget(self.widget, 2, 1, 1, 1)
#        self.VersesPageLayout.addWidget(self.VerseSearchWidget)
#        self.VerseList = QtGui.QTableWidget(self.VersePage)
#        self.VerseList.setObjectName("VerseList")
#        self.VerseList.setColumnCount(0)
#        self.VerseList.setRowCount(0)
#        self.VersesPageLayout.addWidget(self.VerseList)
#        icon8 = QtGui.QIcon()
#        icon8.addPixmap(QtGui.QPixmap(":/media/media_verse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.MediaToolBox.addItem(self.VersePage, icon8, "")
#        self.CustomSlidePage = QtGui.QWidget()
#        self.CustomSlidePage.setGeometry(QtCore.QRect(0, 0, 267, 609))
#        self.CustomSlidePage.setObjectName("CustomSlidePage")
#        self.verticalLayout = QtGui.QVBoxLayout(self.CustomSlidePage)
#        self.verticalLayout.setSpacing(0)
#        self.verticalLayout.setMargin(0)
#        self.verticalLayout.setObjectName("verticalLayout")
#        self.CustomSlideToolbar = QtGui.QWidget(self.CustomSlidePage)
#        self.CustomSlideToolbar.setObjectName("CustomSlideToolbar")
#        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.CustomSlideToolbar)
#        self.horizontalLayout_2.setSpacing(0)
#        self.horizontalLayout_2.setContentsMargins(0, 2, 0, 0)
#        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
#        self.CustomNewButton = QtGui.QToolButton(self.CustomSlideToolbar)
#        icon9 = QtGui.QIcon()
#        icon9.addPixmap(QtGui.QPixmap(":/custom/custom_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.CustomNewButton.setIcon(icon9)
#        self.CustomNewButton.setIconSize(QtCore.QSize(20, 20))
#        self.CustomNewButton.setAutoRaise(True)
#        self.CustomNewButton.setObjectName("CustomNewButton")
#        self.horizontalLayout_2.addWidget(self.CustomNewButton)
#        self.CustomEditButton = QtGui.QToolButton(self.CustomSlideToolbar)
#        icon10 = QtGui.QIcon()
#        icon10.addPixmap(QtGui.QPixmap(":/custom/custom_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.CustomEditButton.setIcon(icon10)
#        self.CustomEditButton.setIconSize(QtCore.QSize(20, 20))
#        self.CustomEditButton.setAutoRaise(True)
#        self.CustomEditButton.setObjectName("CustomEditButton")
#        self.horizontalLayout_2.addWidget(self.CustomEditButton)
#        self.CustomDeleteButton = QtGui.QToolButton(self.CustomSlideToolbar)
#        icon11 = QtGui.QIcon()
#        icon11.addPixmap(QtGui.QPixmap(":/custom/custom_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.CustomDeleteButton.setIcon(icon11)
#        self.CustomDeleteButton.setIconSize(QtCore.QSize(20, 20))
#        self.CustomDeleteButton.setAutoRaise(True)
#        self.CustomDeleteButton.setObjectName("CustomDeleteButton")
#        self.horizontalLayout_2.addWidget(self.CustomDeleteButton)
#        self.CustomToolbarLine = QtGui.QFrame(self.CustomSlideToolbar)
#        self.CustomToolbarLine.setFrameShape(QtGui.QFrame.VLine)
#        self.CustomToolbarLine.setFrameShadow(QtGui.QFrame.Sunken)
#        self.CustomToolbarLine.setObjectName("CustomToolbarLine")
#        self.horizontalLayout_2.addWidget(self.CustomToolbarLine)
#        self.CustomPreviewButton = QtGui.QToolButton(self.CustomSlideToolbar)
#        self.CustomPreviewButton.setIcon(icon4)
#        self.CustomPreviewButton.setIconSize(QtCore.QSize(20, 20))
#        self.CustomPreviewButton.setAutoRaise(True)
#        self.CustomPreviewButton.setObjectName("CustomPreviewButton")
#        self.horizontalLayout_2.addWidget(self.CustomPreviewButton)
#        self.CustomLiveButton = QtGui.QToolButton(self.CustomSlideToolbar)
#        self.CustomLiveButton.setIcon(icon5)
#        self.CustomLiveButton.setIconSize(QtCore.QSize(20, 20))
#        self.CustomLiveButton.setAutoRaise(True)
#        self.CustomLiveButton.setObjectName("CustomLiveButton")
#        self.horizontalLayout_2.addWidget(self.CustomLiveButton)
#        self.CustomAddButton = QtGui.QToolButton(self.CustomSlideToolbar)
#        self.CustomAddButton.setIcon(icon6)
#        self.CustomAddButton.setIconSize(QtCore.QSize(20, 20))
#        self.CustomAddButton.setAutoRaise(True)
#        self.CustomAddButton.setObjectName("CustomAddButton")
#        self.horizontalLayout_2.addWidget(self.CustomAddButton)
#        spacerItem3 = QtGui.QSpacerItem(84, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
#        self.horizontalLayout_2.addItem(spacerItem3)
#        self.verticalLayout.addWidget(self.CustomSlideToolbar)
#        self.CustomSlideList = QtGui.QListWidget(self.CustomSlidePage)
#        self.CustomSlideList.setObjectName("CustomSlideList")
#        self.verticalLayout.addWidget(self.CustomSlideList)
#        icon12 = QtGui.QIcon()
#        icon12.addPixmap(QtGui.QPixmap(":/media/media_custom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.MediaToolBox.addItem(self.CustomSlidePage, icon12, "")
#        self.PresentationPage = QtGui.QWidget()
#        self.PresentationPage.setGeometry(QtCore.QRect(0, 0, 267, 609))
#        self.PresentationPage.setObjectName("PresentationPage")
#        self.PresentationsLayout = QtGui.QVBoxLayout(self.PresentationPage)
#        self.PresentationsLayout.setSpacing(0)
#        self.PresentationsLayout.setMargin(0)
#        self.PresentationsLayout.setObjectName("PresentationsLayout")
#        self.PresentationToolbar = QtGui.QWidget(self.PresentationPage)
#        self.PresentationToolbar.setObjectName("PresentationToolbar")
#        self.PresentationToolbarLayout = QtGui.QHBoxLayout(self.PresentationToolbar)
#        self.PresentationToolbarLayout.setSpacing(0)
#        self.PresentationToolbarLayout.setMargin(0)
#        self.PresentationToolbarLayout.setObjectName("PresentationToolbarLayout")
#        self.PresentationLoadItem = QtGui.QToolButton(self.PresentationToolbar)
#        icon13 = QtGui.QIcon()
#        icon13.addPixmap(QtGui.QPixmap(":/videos/video_load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.PresentationLoadItem.setIcon(icon13)
#        self.PresentationLoadItem.setIconSize(QtCore.QSize(20, 20))
#        self.PresentationLoadItem.setAutoRaise(True)
#        self.PresentationLoadItem.setObjectName("PresentationLoadItem")
#        self.PresentationToolbarLayout.addWidget(self.PresentationLoadItem)
#        self.PresentationDeleteItem = QtGui.QToolButton(self.PresentationToolbar)
#        icon14 = QtGui.QIcon()
#        icon14.addPixmap(QtGui.QPixmap(":/videos/video_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.PresentationDeleteItem.setIcon(icon14)
#        self.PresentationDeleteItem.setIconSize(QtCore.QSize(20, 20))
#        self.PresentationDeleteItem.setAutoRaise(True)
#        self.PresentationDeleteItem.setObjectName("PresentationDeleteItem")
#        self.PresentationToolbarLayout.addWidget(self.PresentationDeleteItem)
#        self.PresentationLine = QtGui.QFrame(self.PresentationToolbar)
#        self.PresentationLine.setFrameShape(QtGui.QFrame.VLine)
#        self.PresentationLine.setFrameShadow(QtGui.QFrame.Sunken)
#        self.PresentationLine.setObjectName("PresentationLine")
#        self.PresentationToolbarLayout.addWidget(self.PresentationLine)
#        self.PresentationLiveItem = QtGui.QToolButton(self.PresentationToolbar)
#        self.PresentationLiveItem.setIcon(icon5)
#        self.PresentationLiveItem.setIconSize(QtCore.QSize(20, 20))
#        self.PresentationLiveItem.setAutoRaise(True)
#        self.PresentationLiveItem.setObjectName("PresentationLiveItem")
#        self.PresentationToolbarLayout.addWidget(self.PresentationLiveItem)
#        self.PresentationAddItem = QtGui.QToolButton(self.PresentationToolbar)
#        self.PresentationAddItem.setIcon(icon6)
#        self.PresentationAddItem.setIconSize(QtCore.QSize(20, 20))
#        self.PresentationAddItem.setAutoRaise(True)
#        self.PresentationAddItem.setObjectName("PresentationAddItem")
#        self.PresentationToolbarLayout.addWidget(self.PresentationAddItem)
#        spacerItem4 = QtGui.QSpacerItem(166, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
#        self.PresentationToolbarLayout.addItem(spacerItem4)
#        self.PresentationsLayout.addWidget(self.PresentationToolbar)
#        self.listWidget_2 = QtGui.QListWidget(self.PresentationPage)
#        self.listWidget_2.setObjectName("listWidget_2")
#        self.PresentationsLayout.addWidget(self.listWidget_2)
#        icon15 = QtGui.QIcon()
#        icon15.addPixmap(QtGui.QPixmap(":/media/media_presentation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.MediaToolBox.addItem(self.PresentationPage, icon15, "")
#        self.VideoPage = QtGui.QWidget()
#        self.VideoPage.setGeometry(QtCore.QRect(0, 0, 267, 609))
#        self.VideoPage.setObjectName("VideoPage")
#        self.VideosLayout = QtGui.QVBoxLayout(self.VideoPage)
#        self.VideosLayout.setSpacing(0)
#        self.VideosLayout.setMargin(0)
#        self.VideosLayout.setObjectName("VideosLayout")
#        self.VideoToolbar = QtGui.QWidget(self.VideoPage)
#        self.VideoToolbar.setObjectName("VideoToolbar")
#        self.VideoToolbarLayout = QtGui.QHBoxLayout(self.VideoToolbar)
#        self.VideoToolbarLayout.setSpacing(0)
#        self.VideoToolbarLayout.setMargin(0)
#        self.VideoToolbarLayout.setObjectName("VideoToolbarLayout")
#        self.VideoLoadItem = QtGui.QToolButton(self.VideoToolbar)
#        self.VideoLoadItem.setIcon(icon13)
#        self.VideoLoadItem.setIconSize(QtCore.QSize(20, 20))
#        self.VideoLoadItem.setAutoRaise(True)
#        self.VideoLoadItem.setObjectName("VideoLoadItem")
#        self.VideoToolbarLayout.addWidget(self.VideoLoadItem)
#        self.VideoDeleteItem = QtGui.QToolButton(self.VideoToolbar)
#        self.VideoDeleteItem.setIcon(icon14)
#        self.VideoDeleteItem.setIconSize(QtCore.QSize(20, 20))
#        self.VideoDeleteItem.setAutoRaise(True)
#        self.VideoDeleteItem.setObjectName("VideoDeleteItem")
#        self.VideoToolbarLayout.addWidget(self.VideoDeleteItem)
#        self.VideoLine = QtGui.QFrame(self.VideoToolbar)
#        self.VideoLine.setFrameShape(QtGui.QFrame.VLine)
#        self.VideoLine.setFrameShadow(QtGui.QFrame.Sunken)
#        self.VideoLine.setObjectName("VideoLine")
#        self.VideoToolbarLayout.addWidget(self.VideoLine)
#        self.VideoLiveItem = QtGui.QToolButton(self.VideoToolbar)
#        self.VideoLiveItem.setIcon(icon5)
#        self.VideoLiveItem.setIconSize(QtCore.QSize(20, 20))
#        self.VideoLiveItem.setAutoRaise(True)
#        self.VideoLiveItem.setObjectName("VideoLiveItem")
#        self.VideoToolbarLayout.addWidget(self.VideoLiveItem)
#        self.VideoAddItem = QtGui.QToolButton(self.VideoToolbar)
#        self.VideoAddItem.setIcon(icon6)
#        self.VideoAddItem.setIconSize(QtCore.QSize(20, 20))
#        self.VideoAddItem.setAutoRaise(True)
#        self.VideoAddItem.setObjectName("VideoAddItem")
#        self.VideoToolbarLayout.addWidget(self.VideoAddItem)
#        spacerItem5 = QtGui.QSpacerItem(166, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
#        self.VideoToolbarLayout.addItem(spacerItem5)
#        self.VideosLayout.addWidget(self.VideoToolbar)
#        self.listWidget = QtGui.QListWidget(self.VideoPage)
#        self.listWidget.setObjectName("listWidget")
#        self.VideosLayout.addWidget(self.listWidget)
#        icon16 = QtGui.QIcon()
#        icon16.addPixmap(QtGui.QPixmap(":/media/media_video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.MediaToolBox.addItem(self.VideoPage, icon16, "")
#        self.ImagePage = QtGui.QWidget()
#        self.ImagePage.setGeometry(QtCore.QRect(0, 0, 267, 609))
#        self.ImagePage.setObjectName("ImagePage")
#        self.ImagesLayout = QtGui.QVBoxLayout(self.ImagePage)
#        self.ImagesLayout.setSpacing(0)
#        self.ImagesLayout.setMargin(0)
#        self.ImagesLayout.setObjectName("ImagesLayout")
#        self.ImageToolbar = QtGui.QWidget(self.ImagePage)
#        self.ImageToolbar.setObjectName("ImageToolbar")
#        self.ImageToolbarLayout = QtGui.QHBoxLayout(self.ImageToolbar)
#        self.ImageToolbarLayout.setSpacing(0)
#        self.ImageToolbarLayout.setMargin(0)
#        self.ImageToolbarLayout.setObjectName("ImageToolbarLayout")
#        self.ImageLoadItem = QtGui.QToolButton(self.ImageToolbar)
#        icon17 = QtGui.QIcon()
#        icon17.addPixmap(QtGui.QPixmap(":/images/image_load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.ImageLoadItem.setIcon(icon17)
#        self.ImageLoadItem.setIconSize(QtCore.QSize(20, 20))
#        self.ImageLoadItem.setAutoRaise(True)
#        self.ImageLoadItem.setObjectName("ImageLoadItem")
#        self.ImageToolbarLayout.addWidget(self.ImageLoadItem)
#        self.ImageDeleteItem = QtGui.QToolButton(self.ImageToolbar)
#        icon18 = QtGui.QIcon()
#        icon18.addPixmap(QtGui.QPixmap(":/images/image_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.ImageDeleteItem.setIcon(icon18)
#        self.ImageDeleteItem.setIconSize(QtCore.QSize(20, 20))
#        self.ImageDeleteItem.setAutoRaise(True)
#        self.ImageDeleteItem.setObjectName("ImageDeleteItem")
#        self.ImageToolbarLayout.addWidget(self.ImageDeleteItem)
#        self.ImageLine = QtGui.QFrame(self.ImageToolbar)
#        self.ImageLine.setFrameShape(QtGui.QFrame.VLine)
#        self.ImageLine.setFrameShadow(QtGui.QFrame.Sunken)
#        self.ImageLine.setObjectName("ImageLine")
#        self.ImageToolbarLayout.addWidget(self.ImageLine)
#        self.ImageLiveItem = QtGui.QToolButton(self.ImageToolbar)
#        self.ImageLiveItem.setIcon(icon5)
#        self.ImageLiveItem.setIconSize(QtCore.QSize(20, 20))
#        self.ImageLiveItem.setAutoRaise(True)
#        self.ImageLiveItem.setObjectName("ImageLiveItem")
#        self.ImageToolbarLayout.addWidget(self.ImageLiveItem)
#        self.ImageAddItem = QtGui.QToolButton(self.ImageToolbar)
#        self.ImageAddItem.setIcon(icon6)
#        self.ImageAddItem.setIconSize(QtCore.QSize(20, 20))
#        self.ImageAddItem.setAutoRaise(True)
#        self.ImageAddItem.setObjectName("ImageAddItem")
#        self.ImageToolbarLayout.addWidget(self.ImageAddItem)
#        spacerItem6 = QtGui.QSpacerItem(105, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
#        self.ImageToolbarLayout.addItem(spacerItem6)
#        self.ImagesLayout.addWidget(self.ImageToolbar)
#        self.ImageListView = QtGui.QListWidget(self.ImagePage)
#        self.ImageListView.setObjectName("ImageListView")
#        self.ImagesLayout.addWidget(self.ImageListView)
#        icon19 = QtGui.QIcon()
#        icon19.addPixmap(QtGui.QPixmap(":/media/media_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#        self.MediaToolBox.addItem(self.ImagePage, icon19, "")
#        self.SongNewItem.setText(QtGui.QApplication.translate("main_window", "New Song", None, QtGui.QApplication.UnicodeUTF8))
#        self.SongEditItem.setText(QtGui.QApplication.translate("main_window", "Edit Song", None, QtGui.QApplication.UnicodeUTF8))
#        self.SongDeleteItem.setText(QtGui.QApplication.translate("main_window", "Delete Song", None, QtGui.QApplication.UnicodeUTF8))
#        self.SongPreviewItem.setText(QtGui.QApplication.translate("main_window", "Send to Preview", None, QtGui.QApplication.UnicodeUTF8))
#        self.SongLiveItem.setText(QtGui.QApplication.translate("main_window", "Send to Live", None, QtGui.QApplication.UnicodeUTF8))
#        self.SongAddItem.setText(QtGui.QApplication.translate("main_window", "Add to Service", None, QtGui.QApplication.UnicodeUTF8))
#        self.MediaToolBox.setItemText(self.MediaToolBox.indexOf(self.SongPage), QtGui.QApplication.translate("main_window", "Songs", None, QtGui.QApplication.UnicodeUTF8))
#        self.VersePreviewItem.setText(QtGui.QApplication.translate("main_window", "Send to Preview", None, QtGui.QApplication.UnicodeUTF8))
#        self.VerseLiveItem.setText(QtGui.QApplication.translate("main_window", "Send to Live", None, QtGui.QApplication.UnicodeUTF8))
#        self.VerseAddItem.setText(QtGui.QApplication.translate("main_window", "Add to Service", None, QtGui.QApplication.UnicodeUTF8))
#        self.label.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
#        self.label_2.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
#        self.pushButton.setText(QtGui.QApplication.translate("main_window", "Search", None, QtGui.QApplication.UnicodeUTF8))
#        self.MediaToolBox.setItemText(self.MediaToolBox.indexOf(self.VersePage), QtGui.QApplication.translate("main_window", "Bible Verses", None, QtGui.QApplication.UnicodeUTF8))
#        self.CustomNewButton.setText(QtGui.QApplication.translate("main_window", "New Custom Slide", None, QtGui.QApplication.UnicodeUTF8))
#        self.CustomEditButton.setText(QtGui.QApplication.translate("main_window", "Edit Custom Slide", None, QtGui.QApplication.UnicodeUTF8))
#        self.CustomDeleteButton.setText(QtGui.QApplication.translate("main_window", "Delete Custom Slide", None, QtGui.QApplication.UnicodeUTF8))
#        self.CustomPreviewButton.setText(QtGui.QApplication.translate("main_window", "Preview Custom Slide", None, QtGui.QApplication.UnicodeUTF8))
#        self.CustomLiveButton.setText(QtGui.QApplication.translate("main_window", "Send Live", None, QtGui.QApplication.UnicodeUTF8))
#        self.CustomAddButton.setText(QtGui.QApplication.translate("main_window", "Add To Service", None, QtGui.QApplication.UnicodeUTF8))
#        self.MediaToolBox.setItemText(self.MediaToolBox.indexOf(self.CustomSlidePage), QtGui.QApplication.translate("main_window", "Custom Slides", None, QtGui.QApplication.UnicodeUTF8))
#        self.PresentationLoadItem.setToolTip(QtGui.QApplication.translate("main_window", "Load Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.PresentationLoadItem.setStatusTip(QtGui.QApplication.translate("main_window", "Load a video", None, QtGui.QApplication.UnicodeUTF8))
#        self.PresentationLoadItem.setText(QtGui.QApplication.translate("main_window", "Load Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.PresentationDeleteItem.setToolTip(QtGui.QApplication.translate("main_window", "Remove Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.PresentationDeleteItem.setText(QtGui.QApplication.translate("main_window", "RI", None, QtGui.QApplication.UnicodeUTF8))
#        self.PresentationLiveItem.setText(QtGui.QApplication.translate("main_window", "Send to Live", None, QtGui.QApplication.UnicodeUTF8))
#        self.PresentationAddItem.setText(QtGui.QApplication.translate("main_window", "Add to Service", None, QtGui.QApplication.UnicodeUTF8))
#        self.MediaToolBox.setItemText(self.MediaToolBox.indexOf(self.PresentationPage), QtGui.QApplication.translate("main_window", "Presentations", None, QtGui.QApplication.UnicodeUTF8))
#        self.VideoLoadItem.setToolTip(QtGui.QApplication.translate("main_window", "Load Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.VideoLoadItem.setStatusTip(QtGui.QApplication.translate("main_window", "Load a video", None, QtGui.QApplication.UnicodeUTF8))
#        self.VideoLoadItem.setText(QtGui.QApplication.translate("main_window", "Load Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.VideoDeleteItem.setToolTip(QtGui.QApplication.translate("main_window", "Remove Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.VideoDeleteItem.setText(QtGui.QApplication.translate("main_window", "RI", None, QtGui.QApplication.UnicodeUTF8))
#        self.VideoLiveItem.setToolTip(QtGui.QApplication.translate("main_window", "Go Live!", None, QtGui.QApplication.UnicodeUTF8))
#        self.VideoAddItem.setToolTip(QtGui.QApplication.translate("main_window", "Add to Order of Service", None, QtGui.QApplication.UnicodeUTF8))
#        self.MediaToolBox.setItemText(self.MediaToolBox.indexOf(self.VideoPage), QtGui.QApplication.translate("main_window", "Videos", None, QtGui.QApplication.UnicodeUTF8))
#        self.ImageLoadItem.setToolTip(QtGui.QApplication.translate("main_window", "Load Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.ImageLoadItem.setStatusTip(QtGui.QApplication.translate("main_window", "Load a video", None, QtGui.QApplication.UnicodeUTF8))
#        self.ImageLoadItem.setText(QtGui.QApplication.translate("main_window", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
#        self.ImageDeleteItem.setToolTip(QtGui.QApplication.translate("main_window", "Remove Video", None, QtGui.QApplication.UnicodeUTF8))
#        self.ImageDeleteItem.setText(QtGui.QApplication.translate("main_window", "Delete Image", None, QtGui.QApplication.UnicodeUTF8))
#        self.ImageLiveItem.setToolTip(QtGui.QApplication.translate("main_window", "Go Live!", None, QtGui.QApplication.UnicodeUTF8))
#        self.ImageAddItem.setToolTip(QtGui.QApplication.translate("main_window", "Add to Order of Service", None, QtGui.QApplication.UnicodeUTF8))
#        self.MediaToolBox.setItemText(self.MediaToolBox.indexOf(self.ImagePage), QtGui.QApplication.translate("main_window", "Images", None, QtGui.QApplication.UnicodeUTF8))
