# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'themewizard.ui'
#
# Created: Sat Oct  9 08:32:36 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ThemeWizard(object):
    def setupUi(self, ThemeWizard):
        ThemeWizard.setObjectName("ThemeWizard")
        ThemeWizard.resize(550, 386)
        ThemeWizard.setModal(True)
        ThemeWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        ThemeWizard.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.welcomePage = QtGui.QWizardPage()
        self.welcomePage.setTitle("")
        self.welcomePage.setSubTitle("")
        self.welcomePage.setObjectName("welcomePage")
        self.welcomeLayout = QtGui.QHBoxLayout(self.welcomePage)
        self.welcomeLayout.setSpacing(8)
        self.welcomeLayout.setMargin(0)
        self.welcomeLayout.setObjectName("welcomeLayout")
        self.importBibleImage = QtGui.QLabel(self.welcomePage)
        self.importBibleImage.setMinimumSize(QtCore.QSize(163, 0))
        self.importBibleImage.setMaximumSize(QtCore.QSize(163, 16777215))
        self.importBibleImage.setLineWidth(0)
        self.importBibleImage.setText("")
        self.importBibleImage.setPixmap(QtGui.QPixmap(":/wizards/wizard_importbible.bmp"))
        self.importBibleImage.setIndent(0)
        self.importBibleImage.setObjectName("importBibleImage")
        self.welcomeLayout.addWidget(self.importBibleImage)
        self.welcomePageLayout = QtGui.QVBoxLayout()
        self.welcomePageLayout.setSpacing(8)
        self.welcomePageLayout.setObjectName("welcomePageLayout")
        self.titleLabel = QtGui.QLabel(self.welcomePage)
        self.titleLabel.setObjectName("titleLabel")
        self.welcomePageLayout.addWidget(self.titleLabel)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.welcomePageLayout.addItem(spacerItem)
        self.informationLabel = QtGui.QLabel(self.welcomePage)
        self.informationLabel.setWordWrap(True)
        self.informationLabel.setMargin(10)
        self.informationLabel.setObjectName("informationLabel")
        self.welcomePageLayout.addWidget(self.informationLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.welcomePageLayout.addItem(spacerItem1)
        self.welcomeLayout.addLayout(self.welcomePageLayout)
        ThemeWizard.addPage(self.welcomePage)
        self.backgroundPage = QtGui.QWizardPage()
        self.backgroundPage.setObjectName("backgroundPage")
        self.backgroundLayout = QtGui.QFormLayout(self.backgroundPage)
        self.backgroundLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.backgroundLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backgroundLayout.setMargin(20)
        self.backgroundLayout.setSpacing(8)
        self.backgroundLayout.setObjectName("backgroundLayout")
        self.backgroundTypeLabel = QtGui.QLabel(self.backgroundPage)
        self.backgroundTypeLabel.setObjectName("backgroundTypeLabel")
        self.backgroundLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.backgroundTypeLabel)
        self.backgroundTypeComboBox = QtGui.QComboBox(self.backgroundPage)
        self.backgroundTypeComboBox.setObjectName("backgroundTypeComboBox")
        self.backgroundTypeComboBox.addItem("")
        self.backgroundTypeComboBox.addItem("")
        self.backgroundTypeComboBox.addItem("")
        self.backgroundLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.backgroundTypeComboBox)
        self.color1Label = QtGui.QLabel(self.backgroundPage)
        self.color1Label.setObjectName("color1Label")
        self.backgroundLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.color1Label)
        self.color1PushButton = QtGui.QPushButton(self.backgroundPage)
        self.color1PushButton.setText("")
        self.color1PushButton.setObjectName("color1PushButton")
        self.backgroundLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.color1PushButton)
        self.color2Label = QtGui.QLabel(self.backgroundPage)
        self.color2Label.setObjectName("color2Label")
        self.backgroundLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.color2Label)
        self.color2PushButton = QtGui.QPushButton(self.backgroundPage)
        self.color2PushButton.setText("")
        self.color2PushButton.setObjectName("color2PushButton")
        self.backgroundLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.color2PushButton)
        self.imageLabel = QtGui.QLabel(self.backgroundPage)
        self.imageLabel.setObjectName("imageLabel")
        self.backgroundLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.imageLabel)
        self.imageLayout = QtGui.QHBoxLayout()
        self.imageLayout.setSpacing(8)
        self.imageLayout.setObjectName("imageLayout")
        self.imageLineEdit = QtGui.QLineEdit(self.backgroundPage)
        self.imageLineEdit.setObjectName("imageLineEdit")
        self.imageLayout.addWidget(self.imageLineEdit)
        self.imageBrowseButton = QtGui.QToolButton(self.backgroundPage)
        self.imageBrowseButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/general/general_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageBrowseButton.setIcon(icon)
        self.imageBrowseButton.setObjectName("imageBrowseButton")
        self.imageLayout.addWidget(self.imageBrowseButton)
        self.backgroundLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.imageLayout)
        self.gradientLabel = QtGui.QLabel(self.backgroundPage)
        self.gradientLabel.setObjectName("gradientLabel")
        self.backgroundLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.gradientLabel)
        self.gradientComboBox = QtGui.QComboBox(self.backgroundPage)
        self.gradientComboBox.setObjectName("gradientComboBox")
        self.gradientComboBox.addItem("")
        self.gradientComboBox.addItem("")
        self.gradientComboBox.addItem("")
        self.gradientComboBox.addItem("")
        self.gradientComboBox.addItem("")
        self.backgroundLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.gradientComboBox)
        ThemeWizard.addPage(self.backgroundPage)
        self.mainAreaPage = QtGui.QWizardPage()
        self.mainAreaPage.setObjectName("mainAreaPage")
        self.formLayout = QtGui.QFormLayout(self.mainAreaPage)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(-1, 20, 20, 20)
        self.formLayout.setSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.mainFontLabel = QtGui.QLabel(self.mainAreaPage)
        self.mainFontLabel.setObjectName("mainFontLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.mainFontLabel)
        self.mainFontComboBox = QtGui.QFontComboBox(self.mainAreaPage)
        self.mainFontComboBox.setObjectName("mainFontComboBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.mainFontComboBox)
        self.mainColorLabel = QtGui.QLabel(self.mainAreaPage)
        self.mainColorLabel.setObjectName("mainColorLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.mainColorLabel)
        self.mainColorPushButton = QtGui.QPushButton(self.mainAreaPage)
        self.mainColorPushButton.setText("")
        self.mainColorPushButton.setObjectName("mainColorPushButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mainColorPushButton)
        self.mainSizeLabel = QtGui.QLabel(self.mainAreaPage)
        self.mainSizeLabel.setObjectName("mainSizeLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.mainSizeLabel)
        self.mainSizeLayout = QtGui.QHBoxLayout()
        self.mainSizeLayout.setSpacing(8)
        self.mainSizeLayout.setMargin(0)
        self.mainSizeLayout.setObjectName("mainSizeLayout")
        self.mainSizeSpinBox = QtGui.QSpinBox(self.mainAreaPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSizeSpinBox.sizePolicy().hasHeightForWidth())
        self.mainSizeSpinBox.setSizePolicy(sizePolicy)
        self.mainSizeSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.mainSizeSpinBox.setMaximum(999)
        self.mainSizeSpinBox.setProperty("value", 16)
        self.mainSizeSpinBox.setObjectName("mainSizeSpinBox")
        self.mainSizeLayout.addWidget(self.mainSizeSpinBox)
        self.mainLineCountLabel = QtGui.QLabel(self.mainAreaPage)
        self.mainLineCountLabel.setObjectName("mainLineCountLabel")
        self.mainSizeLayout.addWidget(self.mainLineCountLabel)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.mainSizeLayout)
        self.lineSpacingLabel = QtGui.QLabel(self.mainAreaPage)
        self.lineSpacingLabel.setObjectName("lineSpacingLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lineSpacingLabel)
        self.lineSpacingSpinBox = QtGui.QSpinBox(self.mainAreaPage)
        self.lineSpacingSpinBox.setMinimum(-50)
        self.lineSpacingSpinBox.setMaximum(50)
        self.lineSpacingSpinBox.setObjectName("lineSpacingSpinBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineSpacingSpinBox)
        self.outlineCheckBox = QtGui.QCheckBox(self.mainAreaPage)
        self.outlineCheckBox.setObjectName("outlineCheckBox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.outlineCheckBox)
        self.outlineLayout = QtGui.QHBoxLayout()
        self.outlineLayout.setObjectName("outlineLayout")
        self.outlineColorPushButton = QtGui.QPushButton(self.mainAreaPage)
        self.outlineColorPushButton.setEnabled(True)
        self.outlineColorPushButton.setText("")
        self.outlineColorPushButton.setObjectName("outlineColorPushButton")
        self.outlineLayout.addWidget(self.outlineColorPushButton)
        self.outlineSizeLabel = QtGui.QLabel(self.mainAreaPage)
        self.outlineSizeLabel.setObjectName("outlineSizeLabel")
        self.outlineLayout.addWidget(self.outlineSizeLabel)
        self.outlineSizeSpinBox = QtGui.QSpinBox(self.mainAreaPage)
        self.outlineSizeSpinBox.setObjectName("outlineSizeSpinBox")
        self.outlineLayout.addWidget(self.outlineSizeSpinBox)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.outlineLayout)
        self.shadowCheckBox = QtGui.QCheckBox(self.mainAreaPage)
        self.shadowCheckBox.setObjectName("shadowCheckBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.shadowCheckBox)
        self.shadowLayout = QtGui.QHBoxLayout()
        self.shadowLayout.setObjectName("shadowLayout")
        self.shadowColorPushButton = QtGui.QPushButton(self.mainAreaPage)
        self.shadowColorPushButton.setEnabled(True)
        self.shadowColorPushButton.setText("")
        self.shadowColorPushButton.setObjectName("shadowColorPushButton")
        self.shadowLayout.addWidget(self.shadowColorPushButton)
        self.shadowSizeLabel = QtGui.QLabel(self.mainAreaPage)
        self.shadowSizeLabel.setObjectName("shadowSizeLabel")
        self.shadowLayout.addWidget(self.shadowSizeLabel)
        self.shadowSizeSpinBox = QtGui.QSpinBox(self.mainAreaPage)
        self.shadowSizeSpinBox.setObjectName("shadowSizeSpinBox")
        self.shadowLayout.addWidget(self.shadowSizeSpinBox)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.shadowLayout)
        ThemeWizard.addPage(self.mainAreaPage)
        self.footerAreaPage = QtGui.QWizardPage()
        self.footerAreaPage.setObjectName("footerAreaPage")
        self.footerLayout = QtGui.QFormLayout(self.footerAreaPage)
        self.footerLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.footerLayout.setContentsMargins(50, 20, 20, 20)
        self.footerLayout.setSpacing(8)
        self.footerLayout.setObjectName("footerLayout")
        self.footerFontLabel = QtGui.QLabel(self.footerAreaPage)
        self.footerFontLabel.setObjectName("footerFontLabel")
        self.footerLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.footerFontLabel)
        self.footerFontComboBox = QtGui.QFontComboBox(self.footerAreaPage)
        self.footerFontComboBox.setObjectName("footerFontComboBox")
        self.footerLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.footerFontComboBox)
        self.footerColorLabel = QtGui.QLabel(self.footerAreaPage)
        self.footerColorLabel.setObjectName("footerColorLabel")
        self.footerLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.footerColorLabel)
        self.footerColorPushButton = QtGui.QPushButton(self.footerAreaPage)
        self.footerColorPushButton.setText("")
        self.footerColorPushButton.setObjectName("footerColorPushButton")
        self.footerLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.footerColorPushButton)
        self.footerSizeLabel = QtGui.QLabel(self.footerAreaPage)
        self.footerSizeLabel.setObjectName("footerSizeLabel")
        self.footerLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.footerSizeLabel)
        self.footerSizeSpinBox = QtGui.QSpinBox(self.footerAreaPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footerSizeSpinBox.sizePolicy().hasHeightForWidth())
        self.footerSizeSpinBox.setSizePolicy(sizePolicy)
        self.footerSizeSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.footerSizeSpinBox.setMaximum(999)
        self.footerSizeSpinBox.setProperty("value", 10)
        self.footerSizeSpinBox.setObjectName("footerSizeSpinBox")
        self.footerLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.footerSizeSpinBox)
        ThemeWizard.addPage(self.footerAreaPage)
        self.alignmentPage = QtGui.QWizardPage()
        self.alignmentPage.setObjectName("alignmentPage")
        ThemeWizard.addPage(self.alignmentPage)
        self.areaPositionPage = QtGui.QWizardPage()
        self.areaPositionPage.setObjectName("areaPositionPage")
        self.gridLayout_2 = QtGui.QGridLayout(self.areaPositionPage)
        self.gridLayout_2.setMargin(20)
        self.gridLayout_2.setSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainPositionGroupBox = QtGui.QGroupBox(self.areaPositionPage)
        self.mainPositionGroupBox.setMinimumSize(QtCore.QSize(248, 0))
        self.mainPositionGroupBox.setObjectName("mainPositionGroupBox")
        self.mainPositionLayout = QtGui.QFormLayout(self.mainPositionGroupBox)
        self.mainPositionLayout.setMargin(8)
        self.mainPositionLayout.setSpacing(8)
        self.mainPositionLayout.setObjectName("mainPositionLayout")
        self.mainDefaultPositionCheckBox = QtGui.QCheckBox(self.mainPositionGroupBox)
        self.mainDefaultPositionCheckBox.setChecked(True)
        self.mainDefaultPositionCheckBox.setTristate(False)
        self.mainDefaultPositionCheckBox.setObjectName("mainDefaultPositionCheckBox")
        self.mainPositionLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.mainDefaultPositionCheckBox)
        self.nainXLabel = QtGui.QLabel(self.mainPositionGroupBox)
        self.nainXLabel.setObjectName("nainXLabel")
        self.mainPositionLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.nainXLabel)
        self.mainXSpinBox = QtGui.QSpinBox(self.mainPositionGroupBox)
        self.mainXSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainXSpinBox.sizePolicy().hasHeightForWidth())
        self.mainXSpinBox.setSizePolicy(sizePolicy)
        self.mainXSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.mainXSpinBox.setMaximum(9999)
        self.mainXSpinBox.setProperty("value", 0)
        self.mainXSpinBox.setObjectName("mainXSpinBox")
        self.mainPositionLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.mainXSpinBox)
        self.mainYSpinBox = QtGui.QSpinBox(self.mainPositionGroupBox)
        self.mainYSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainYSpinBox.sizePolicy().hasHeightForWidth())
        self.mainYSpinBox.setSizePolicy(sizePolicy)
        self.mainYSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.mainYSpinBox.setMaximum(9999)
        self.mainYSpinBox.setObjectName("mainYSpinBox")
        self.mainPositionLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.mainYSpinBox)
        self.mainYLabel = QtGui.QLabel(self.mainPositionGroupBox)
        self.mainYLabel.setObjectName("mainYLabel")
        self.mainPositionLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.mainYLabel)
        self.mainWidthSpinBox = QtGui.QSpinBox(self.mainPositionGroupBox)
        self.mainWidthSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidthSpinBox.sizePolicy().hasHeightForWidth())
        self.mainWidthSpinBox.setSizePolicy(sizePolicy)
        self.mainWidthSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.mainWidthSpinBox.setMaximum(9999)
        self.mainWidthSpinBox.setObjectName("mainWidthSpinBox")
        self.mainPositionLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.mainWidthSpinBox)
        self.mainWidthLabel = QtGui.QLabel(self.mainPositionGroupBox)
        self.mainWidthLabel.setObjectName("mainWidthLabel")
        self.mainPositionLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.mainWidthLabel)
        self.mainHeightSpinBox = QtGui.QSpinBox(self.mainPositionGroupBox)
        self.mainHeightSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainHeightSpinBox.sizePolicy().hasHeightForWidth())
        self.mainHeightSpinBox.setSizePolicy(sizePolicy)
        self.mainHeightSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.mainHeightSpinBox.setMaximum(9999)
        self.mainHeightSpinBox.setObjectName("mainHeightSpinBox")
        self.mainPositionLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.mainHeightSpinBox)
        self.mainHeightLabel = QtGui.QLabel(self.mainPositionGroupBox)
        self.mainHeightLabel.setObjectName("mainHeightLabel")
        self.mainPositionLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.mainHeightLabel)
        self.gridLayout_2.addWidget(self.mainPositionGroupBox, 1, 0, 1, 1)
        self.footerPositionGroupBox = QtGui.QGroupBox(self.areaPositionPage)
        self.footerPositionGroupBox.setMinimumSize(QtCore.QSize(248, 0))
        self.footerPositionGroupBox.setObjectName("footerPositionGroupBox")
        self.footerPositionLayout = QtGui.QFormLayout(self.footerPositionGroupBox)
        self.footerPositionLayout.setMargin(8)
        self.footerPositionLayout.setSpacing(8)
        self.footerPositionLayout.setObjectName("footerPositionLayout")
        self.footerXLabel = QtGui.QLabel(self.footerPositionGroupBox)
        self.footerXLabel.setObjectName("footerXLabel")
        self.footerPositionLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.footerXLabel)
        self.footerXSpinBox = QtGui.QSpinBox(self.footerPositionGroupBox)
        self.footerXSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footerXSpinBox.sizePolicy().hasHeightForWidth())
        self.footerXSpinBox.setSizePolicy(sizePolicy)
        self.footerXSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.footerXSpinBox.setMaximum(9999)
        self.footerXSpinBox.setProperty("value", 0)
        self.footerXSpinBox.setObjectName("footerXSpinBox")
        self.footerPositionLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.footerXSpinBox)
        self.footerYLabel = QtGui.QLabel(self.footerPositionGroupBox)
        self.footerYLabel.setObjectName("footerYLabel")
        self.footerPositionLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.footerYLabel)
        self.footerYSpinBox = QtGui.QSpinBox(self.footerPositionGroupBox)
        self.footerYSpinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footerYSpinBox.sizePolicy().hasHeightForWidth())
        self.footerYSpinBox.setSizePolicy(sizePolicy)
        self.footerYSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.footerYSpinBox.setMaximum(9999)
        self.footerYSpinBox.setProperty("value", 0)
        self.footerYSpinBox.setObjectName("footerYSpinBox")
        self.footerPositionLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.footerYSpinBox)
        self.footerWidthLabel = QtGui.QLabel(self.footerPositionGroupBox)
        self.footerWidthLabel.setObjectName("footerWidthLabel")
        self.footerPositionLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.footerWidthLabel)
        self.footerWidthSpinBox = QtGui.QSpinBox(self.footerPositionGroupBox)
        self.footerWidthSpinBox.setEnabled(False)
        self.footerWidthSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.footerWidthSpinBox.setMaximum(9999)
        self.footerWidthSpinBox.setObjectName("footerWidthSpinBox")
        self.footerPositionLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.footerWidthSpinBox)
        self.footerHeightLabel = QtGui.QLabel(self.footerPositionGroupBox)
        self.footerHeightLabel.setObjectName("footerHeightLabel")
        self.footerPositionLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.footerHeightLabel)
        self.footerHeightSpinBox = QtGui.QSpinBox(self.footerPositionGroupBox)
        self.footerHeightSpinBox.setEnabled(False)
        self.footerHeightSpinBox.setMinimumSize(QtCore.QSize(78, 0))
        self.footerHeightSpinBox.setMaximum(9999)
        self.footerHeightSpinBox.setObjectName("footerHeightSpinBox")
        self.footerPositionLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.footerHeightSpinBox)
        self.footerDefaultPositionCheckBox = QtGui.QCheckBox(self.footerPositionGroupBox)
        self.footerDefaultPositionCheckBox.setChecked(True)
        self.footerDefaultPositionCheckBox.setObjectName("footerDefaultPositionCheckBox")
        self.footerPositionLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.footerDefaultPositionCheckBox)
        self.gridLayout_2.addWidget(self.footerPositionGroupBox, 1, 1, 1, 1)
        ThemeWizard.addPage(self.areaPositionPage)
        self.previewPage = QtGui.QWizardPage()
        self.previewPage.setObjectName("previewPage")
        self.previewLayout = QtGui.QGridLayout(self.previewPage)
        self.previewLayout.setMargin(20)
        self.previewLayout.setSpacing(8)
        self.previewLayout.setObjectName("previewLayout")
        self.themeNameLabel = QtGui.QLabel(self.previewPage)
        self.themeNameLabel.setTextFormat(QtCore.Qt.PlainText)
        self.themeNameLabel.setObjectName("themeNameLabel")
        self.previewLayout.addWidget(self.themeNameLabel, 0, 0, 1, 1)
        self.previewLabel = QtGui.QLabel(self.previewPage)
        self.previewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.previewLabel.setObjectName("previewLabel")
        self.previewLayout.addWidget(self.previewLabel, 2, 0, 1, 2)
        self.themeNameEdit = QtGui.QLineEdit(self.previewPage)
        self.themeNameEdit.setObjectName("themeNameEdit")
        self.previewLayout.addWidget(self.themeNameEdit, 0, 1, 1, 1)
        self.previewBoxLayout = QtGui.QHBoxLayout()
        self.previewBoxLayout.setSpacing(0)
        self.previewBoxLayout.setContentsMargins(0, 0, -1, -1)
        self.previewBoxLayout.setObjectName("previewBoxLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.previewBoxLayout.addItem(spacerItem2)
        self.previewBoxLabel = QtGui.QLabel(self.previewPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewBoxLabel.sizePolicy().hasHeightForWidth())
        self.previewBoxLabel.setSizePolicy(sizePolicy)
        self.previewBoxLabel.setMinimumSize(QtCore.QSize(300, 200))
        self.previewBoxLabel.setFrameShape(QtGui.QFrame.WinPanel)
        self.previewBoxLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.previewBoxLabel.setLineWidth(1)
        self.previewBoxLabel.setText("")
        self.previewBoxLabel.setScaledContents(True)
        self.previewBoxLabel.setObjectName("previewBoxLabel")
        self.previewBoxLayout.addWidget(self.previewBoxLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.previewBoxLayout.addItem(spacerItem3)
        self.previewLayout.addLayout(self.previewBoxLayout, 3, 0, 1, 2)
        ThemeWizard.addPage(self.previewPage)
        self.themeNameLabel.setBuddy(self.themeNameEdit)

        self.retranslateUi(ThemeWizard)
        QtCore.QMetaObject.connectSlotsByName(ThemeWizard)

    def retranslateUi(self, ThemeWizard):
        ThemeWizard.setWindowTitle(QtGui.QApplication.translate("ThemeWizard", "Theme Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("ThemeWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Welcome to the Theme Wizard</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.informationLabel.setText(QtGui.QApplication.translate("ThemeWizard", "This wizard will help you to maintain Themes . Click the next button below to start the process by setting up your background.", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundPage.setTitle(QtGui.QApplication.translate("ThemeWizard", "Set Up Background", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundPage.setSubTitle(QtGui.QApplication.translate("ThemeWizard", "Set up your theme\'s background according to the parameters below.", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundTypeLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Background type:", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundTypeComboBox.setItemText(0, QtGui.QApplication.translate("ThemeWizard", "Solid Color", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundTypeComboBox.setItemText(1, QtGui.QApplication.translate("ThemeWizard", "Gradient", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundTypeComboBox.setItemText(2, QtGui.QApplication.translate("ThemeWizard", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.color1Label.setText(QtGui.QApplication.translate("ThemeWizard", "<Color1>", None, QtGui.QApplication.UnicodeUTF8))
        self.color2Label.setText(QtGui.QApplication.translate("ThemeWizard", "<Color2>", None, QtGui.QApplication.UnicodeUTF8))
        self.imageLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Image:", None, QtGui.QApplication.UnicodeUTF8))
        self.gradientLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Gradient:", None, QtGui.QApplication.UnicodeUTF8))
        self.gradientComboBox.setItemText(0, QtGui.QApplication.translate("ThemeWizard", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.gradientComboBox.setItemText(1, QtGui.QApplication.translate("ThemeWizard", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.gradientComboBox.setItemText(2, QtGui.QApplication.translate("ThemeWizard", "Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.gradientComboBox.setItemText(3, QtGui.QApplication.translate("ThemeWizard", "Top Left - Bottom Right", None, QtGui.QApplication.UnicodeUTF8))
        self.gradientComboBox.setItemText(4, QtGui.QApplication.translate("ThemeWizard", "Bottom Left - Top Right", None, QtGui.QApplication.UnicodeUTF8))
        self.mainAreaPage.setTitle(QtGui.QApplication.translate("ThemeWizard", "Main Area Font Details", None, QtGui.QApplication.UnicodeUTF8))
        self.mainAreaPage.setSubTitle(QtGui.QApplication.translate("ThemeWizard", "Define the font and display characteristics for the Display text", None, QtGui.QApplication.UnicodeUTF8))
        self.mainFontLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.mainColorLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.mainSizeLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.mainSizeSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.mainLineCountLabel.setText(QtGui.QApplication.translate("ThemeWizard", "(%d lines per slide)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpacingLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Line Spacing:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSpacingSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.outlineCheckBox.setText(QtGui.QApplication.translate("ThemeWizard", "&Outline:", None, QtGui.QApplication.UnicodeUTF8))
        self.outlineSizeLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.outlineSizeSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.shadowCheckBox.setText(QtGui.QApplication.translate("ThemeWizard", "&Shadow:", None, QtGui.QApplication.UnicodeUTF8))
        self.shadowSizeLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.shadowSizeSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.footerAreaPage.setTitle(QtGui.QApplication.translate("ThemeWizard", "Footer Area Font Details", None, QtGui.QApplication.UnicodeUTF8))
        self.footerAreaPage.setSubTitle(QtGui.QApplication.translate("ThemeWizard", "Define the font and display characteristics for the Footer text", None, QtGui.QApplication.UnicodeUTF8))
        self.footerFontLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Font:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerColorLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerSizeLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerSizeSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.alignmentPage.setTitle(QtGui.QApplication.translate("ThemeWizard", "Text Formatting Details", None, QtGui.QApplication.UnicodeUTF8))
        self.alignmentPage.setSubTitle(QtGui.QApplication.translate("ThemeWizard", "Allows additional display formatting information to be defined", None, QtGui.QApplication.UnicodeUTF8))
        self.areaPositionPage.setTitle(QtGui.QApplication.translate("ThemeWizard", "Output Area Locations", None, QtGui.QApplication.UnicodeUTF8))
        self.areaPositionPage.setSubTitle(QtGui.QApplication.translate("ThemeWizard", "Allows you to change and move the Main and Footer areas.", None, QtGui.QApplication.UnicodeUTF8))
        self.mainPositionGroupBox.setTitle(QtGui.QApplication.translate("ThemeWizard", "&Main Area", None, QtGui.QApplication.UnicodeUTF8))
        self.mainDefaultPositionCheckBox.setText(QtGui.QApplication.translate("ThemeWizard", "&Use default location", None, QtGui.QApplication.UnicodeUTF8))
        self.nainXLabel.setText(QtGui.QApplication.translate("ThemeWizard", "X position:", None, QtGui.QApplication.UnicodeUTF8))
        self.mainXSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.mainYSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.mainYLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Y position:", None, QtGui.QApplication.UnicodeUTF8))
        self.mainWidthSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.mainWidthLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.mainHeightSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.mainHeightLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerPositionGroupBox.setTitle(QtGui.QApplication.translate("ThemeWizard", "Footer Area", None, QtGui.QApplication.UnicodeUTF8))
        self.footerXLabel.setText(QtGui.QApplication.translate("ThemeWizard", "X position:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerXSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.footerYLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Y position:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerYSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.footerWidthLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerWidthSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.footerHeightLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.footerHeightSpinBox.setSuffix(QtGui.QApplication.translate("ThemeWizard", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.footerDefaultPositionCheckBox.setText(QtGui.QApplication.translate("ThemeWizard", "Use default location", None, QtGui.QApplication.UnicodeUTF8))
        self.previewPage.setTitle(QtGui.QApplication.translate("ThemeWizard", "Save and Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.previewPage.setSubTitle(QtGui.QApplication.translate("ThemeWizard", "View the theme and save it replacing the current one or change the name to create a new theme", None, QtGui.QApplication.UnicodeUTF8))
        self.themeNameLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Theme name:", None, QtGui.QApplication.UnicodeUTF8))
        self.previewLabel.setText(QtGui.QApplication.translate("ThemeWizard", "Preview", None, QtGui.QApplication.UnicodeUTF8))

