# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displaytabdialog.ui'
#
# Created: Sun Feb 20 17:37:30 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_displayTagEdit(object):
    def setupUi(self, displayTagEdit):
        displayTagEdit.setObjectName(_fromUtf8("displayTagEdit"))
        displayTagEdit.resize(725, 548)
        self.widget = QtGui.QWidget(displayTagEdit)
        self.widget.setGeometry(QtCore.QRect(10, 10, 701, 521))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tagTableWidget = QtGui.QTableWidget(self.widget)
        self.tagTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tagTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tagTableWidget.setAlternatingRowColors(True)
        self.tagTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tagTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tagTableWidget.setCornerButtonEnabled(False)
        self.tagTableWidget.setObjectName(_fromUtf8("tagTableWidget"))
        self.tagTableWidget.setColumnCount(4)
        self.tagTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tagTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tagTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tagTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tagTableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.tagTableWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.defaultPushButton = QtGui.QPushButton(self.widget)
        self.defaultPushButton.setObjectName(_fromUtf8("defaultPushButton"))
        self.horizontalLayout.addWidget(self.defaultPushButton)
        self.deletePushButton = QtGui.QPushButton(self.widget)
        self.deletePushButton.setObjectName(_fromUtf8("deletePushButton"))
        self.horizontalLayout.addWidget(self.deletePushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.editGroupBox = QtGui.QGroupBox(self.widget)
        self.editGroupBox.setObjectName(_fromUtf8("editGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.editGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.descriptionLabel = QtGui.QLabel(self.editGroupBox)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.gridLayout.addWidget(self.descriptionLabel, 0, 0, 1, 1)
        self.descriptionLineEdit = QtGui.QLineEdit(self.editGroupBox)
        self.descriptionLineEdit.setObjectName(_fromUtf8("descriptionLineEdit"))
        self.gridLayout.addWidget(self.descriptionLineEdit, 0, 1, 2, 1)
        self.addPushButton = QtGui.QPushButton(self.editGroupBox)
        self.addPushButton.setObjectName(_fromUtf8("addPushButton"))
        self.gridLayout.addWidget(self.addPushButton, 0, 2, 1, 1)
        self.newPushButton = QtGui.QPushButton(self.editGroupBox)
        self.newPushButton.setObjectName(_fromUtf8("newPushButton"))
        self.gridLayout.addWidget(self.newPushButton, 1, 2, 2, 1)
        self.tagLabel = QtGui.QLabel(self.editGroupBox)
        self.tagLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tagLabel.setObjectName(_fromUtf8("tagLabel"))
        self.gridLayout.addWidget(self.tagLabel, 2, 0, 1, 1)
        self.tagLineEdit = QtGui.QLineEdit(self.editGroupBox)
        self.tagLineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tagLineEdit.setMaxLength(5)
        self.tagLineEdit.setObjectName(_fromUtf8("tagLineEdit"))
        self.gridLayout.addWidget(self.tagLineEdit, 2, 1, 1, 1)
        self.startTagLabel = QtGui.QLabel(self.editGroupBox)
        self.startTagLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startTagLabel.setObjectName(_fromUtf8("startTagLabel"))
        self.gridLayout.addWidget(self.startTagLabel, 3, 0, 1, 1)
        self.startTagLineEdit = QtGui.QLineEdit(self.editGroupBox)
        self.startTagLineEdit.setObjectName(_fromUtf8("startTagLineEdit"))
        self.gridLayout.addWidget(self.startTagLineEdit, 3, 1, 1, 1)
        self.endTagLabel = QtGui.QLabel(self.editGroupBox)
        self.endTagLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endTagLabel.setObjectName(_fromUtf8("endTagLabel"))
        self.gridLayout.addWidget(self.endTagLabel, 4, 0, 1, 1)
        self.endTagLineEdit = QtGui.QLineEdit(self.editGroupBox)
        self.endTagLineEdit.setObjectName(_fromUtf8("endTagLineEdit"))
        self.gridLayout.addWidget(self.endTagLineEdit, 4, 1, 1, 1)
        self.updatePushButton = QtGui.QPushButton(self.editGroupBox)
        self.updatePushButton.setObjectName(_fromUtf8("updatePushButton"))
        self.gridLayout.addWidget(self.updatePushButton, 4, 2, 1, 1)
        self.gridLayout_2.addWidget(self.editGroupBox, 2, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 1)

        self.retranslateUi(displayTagEdit)
        QtCore.QMetaObject.connectSlotsByName(displayTagEdit)

    def retranslateUi(self, displayTagEdit):
        displayTagEdit.setWindowTitle(QtGui.QApplication.translate("displayTagEdit", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tagTableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("displayTagEdit", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tagTableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("displayTagEdit", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.tagTableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("displayTagEdit", "Start Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.tagTableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("displayTagEdit", "End Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultPushButton.setText(QtGui.QApplication.translate("displayTagEdit", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.deletePushButton.setText(QtGui.QApplication.translate("displayTagEdit", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.editGroupBox.setTitle(QtGui.QApplication.translate("displayTagEdit", "Edit Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionLabel.setText(QtGui.QApplication.translate("displayTagEdit", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.addPushButton.setText(QtGui.QApplication.translate("displayTagEdit", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.newPushButton.setText(QtGui.QApplication.translate("displayTagEdit", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.tagLabel.setText(QtGui.QApplication.translate("displayTagEdit", "Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.startTagLabel.setText(QtGui.QApplication.translate("displayTagEdit", "Start tag", None, QtGui.QApplication.UnicodeUTF8))
        self.endTagLabel.setText(QtGui.QApplication.translate("displayTagEdit", "End tag", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePushButton.setText(QtGui.QApplication.translate("displayTagEdit", "Update", None, QtGui.QApplication.UnicodeUTF8))

