# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editversedialog.ui'
#
# Created: Wed Dec  2 08:14:47 2009
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EditVerseDialog(object):
    def setupUi(self, EditVerseDialog):
        EditVerseDialog.setObjectName("EditVerseDialog")
        EditVerseDialog.resize(500, 521)
        EditVerseDialog.setModal(True)
        self.layoutWidget = QtGui.QWidget(EditVerseDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 1, 471, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.VerseTypeLabel = QtGui.QLabel(self.layoutWidget)
        self.VerseTypeLabel.setTextFormat(QtCore.Qt.PlainText)
        self.VerseTypeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VerseTypeLabel.setObjectName("VerseTypeLabel")
        self.verticalLayout.addWidget(self.VerseTypeLabel)
        self.VerseListComboBox = QtGui.QComboBox(self.layoutWidget)
        self.VerseListComboBox.setObjectName("VerseListComboBox")
        self.VerseListComboBox.addItem("")
        self.VerseListComboBox.addItem("")
        self.VerseListComboBox.addItem("")
        self.VerseListComboBox.addItem("")
        self.VerseListComboBox.addItem("")
        self.VerseListComboBox.addItem("")
        self.VerseListComboBox.addItem("")
        self.verticalLayout.addWidget(self.VerseListComboBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VerseNumberLabel = QtGui.QLabel(self.layoutWidget)
        self.VerseNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VerseNumberLabel.setObjectName("VerseNumberLabel")
        self.verticalLayout_2.addWidget(self.VerseNumberLabel)
        self.SubVerseListComboBox = QtGui.QComboBox(self.layoutWidget)
        self.SubVerseListComboBox.setObjectName("SubVerseListComboBox")
        self.verticalLayout_2.addWidget(self.SubVerseListComboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.VerseTextEdit = QtGui.QTextEdit(self.layoutWidget)
        self.VerseTextEdit.setAcceptRichText(False)
        self.VerseTextEdit.setObjectName("VerseTextEdit")
        self.verticalLayout_3.addWidget(self.VerseTextEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addBridge = QtGui.QPushButton(self.layoutWidget)
        self.addBridge.setObjectName("addBridge")
        self.horizontalLayout_2.addWidget(self.addBridge)
        self.addVerse = QtGui.QPushButton(self.layoutWidget)
        self.addVerse.setObjectName("addVerse")
        self.horizontalLayout_2.addWidget(self.addVerse)
        self.addChorus = QtGui.QPushButton(self.layoutWidget)
        self.addChorus.setObjectName("addChorus")
        self.horizontalLayout_2.addWidget(self.addChorus)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addPreChorus = QtGui.QPushButton(self.layoutWidget)
        self.addPreChorus.setObjectName("addPreChorus")
        self.horizontalLayout_3.addWidget(self.addPreChorus)
        self.addIntro = QtGui.QPushButton(self.layoutWidget)
        self.addIntro.setObjectName("addIntro")
        self.horizontalLayout_3.addWidget(self.addIntro)
        self.addOther = QtGui.QPushButton(self.layoutWidget)
        self.addOther.setObjectName("addOther")
        self.horizontalLayout_3.addWidget(self.addOther)
        self.addEnding = QtGui.QPushButton(self.layoutWidget)
        self.addEnding.setObjectName("addEnding")
        self.horizontalLayout_3.addWidget(self.addEnding)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.ButtonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.ButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.ButtonBox.setObjectName("ButtonBox")
        self.verticalLayout_3.addWidget(self.ButtonBox)

        self.retranslateUi(EditVerseDialog)
        QtCore.QObject.connect(self.ButtonBox, QtCore.SIGNAL("accepted()"), EditVerseDialog.accept)
        QtCore.QObject.connect(self.ButtonBox, QtCore.SIGNAL("rejected()"), EditVerseDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditVerseDialog)

    def retranslateUi(self, EditVerseDialog):
        EditVerseDialog.setWindowTitle(QtGui.QApplication.translate("EditVerseDialog", "Edit Verse", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseTypeLabel.setText(QtGui.QApplication.translate("EditVerseDialog", "Verse Type", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseListComboBox.setItemText(0, QtGui.QApplication.translate("EditVerseDialog", "Intro", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseListComboBox.setItemText(1, QtGui.QApplication.translate("EditVerseDialog", "Verse", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseListComboBox.setItemText(2, QtGui.QApplication.translate("EditVerseDialog", "Pre-Chorus", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseListComboBox.setItemText(3, QtGui.QApplication.translate("EditVerseDialog", "Chorus", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseListComboBox.setItemText(4, QtGui.QApplication.translate("EditVerseDialog", "Bridge", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseListComboBox.setItemText(5, QtGui.QApplication.translate("EditVerseDialog", "Ending", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseListComboBox.setItemText(6, QtGui.QApplication.translate("EditVerseDialog", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseNumberLabel.setText(QtGui.QApplication.translate("EditVerseDialog", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.addBridge.setText(QtGui.QApplication.translate("EditVerseDialog", "Bridge", None, QtGui.QApplication.UnicodeUTF8))
        self.addVerse.setText(QtGui.QApplication.translate("EditVerseDialog", "Verse", None, QtGui.QApplication.UnicodeUTF8))
        self.addChorus.setText(QtGui.QApplication.translate("EditVerseDialog", "Chorus", None, QtGui.QApplication.UnicodeUTF8))
        self.addPreChorus.setText(QtGui.QApplication.translate("EditVerseDialog", "Pre-Chorus", None, QtGui.QApplication.UnicodeUTF8))
        self.addIntro.setText(QtGui.QApplication.translate("EditVerseDialog", "Intro", None, QtGui.QApplication.UnicodeUTF8))
        self.addOther.setText(QtGui.QApplication.translate("EditVerseDialog", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.addEnding.setText(QtGui.QApplication.translate("EditVerseDialog", "Ending", None, QtGui.QApplication.UnicodeUTF8))

