# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editsongdialog.ui'
#
# Created: Fri Jan  9 18:44:05 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EditSongDialog(object):
    def setupUi(self, EditSongDialog):
        EditSongDialog.setObjectName("EditSongDialog")
        EditSongDialog.resize(734, 756)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/openlp.org-icon-32.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EditSongDialog.setWindowIcon(icon)
        self.TopWidget = QtGui.QWidget(EditSongDialog)
        self.TopWidget.setGeometry(QtCore.QRect(8, 8, 711, 721))
        self.TopWidget.setObjectName("TopWidget")
        self.TextWidget = QtGui.QWidget(self.TopWidget)
        self.TextWidget.setGeometry(QtCore.QRect(0, 0, 331, 531))
        self.TextWidget.setObjectName("TextWidget")
        self.gridLayout = QtGui.QGridLayout(self.TextWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TitleLabel = QtGui.QLabel(self.TextWidget)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.TitleEditItem = QtGui.QLineEdit(self.TextWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleEditItem.sizePolicy().hasHeightForWidth())
        self.TitleEditItem.setSizePolicy(sizePolicy)
        self.TitleEditItem.setObjectName("TitleEditItem")
        self.gridLayout.addWidget(self.TitleEditItem, 1, 0, 1, 1)
        self.AlternativeTitleLabel = QtGui.QLabel(self.TextWidget)
        self.AlternativeTitleLabel.setObjectName("AlternativeTitleLabel")
        self.gridLayout.addWidget(self.AlternativeTitleLabel, 2, 0, 1, 1)
        self.AlternativeEdit = QtGui.QLineEdit(self.TextWidget)
        self.AlternativeEdit.setObjectName("AlternativeEdit")
        self.gridLayout.addWidget(self.AlternativeEdit, 3, 0, 1, 1)
        self.LyricsLabel = QtGui.QLabel(self.TextWidget)
        self.LyricsLabel.setObjectName("LyricsLabel")
        self.gridLayout.addWidget(self.LyricsLabel, 6, 0, 1, 1)
        self.LyricsTextEdit = QtGui.QTextEdit(self.TextWidget)
        self.LyricsTextEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.LyricsTextEdit.setAcceptRichText(False)
        self.LyricsTextEdit.setObjectName("LyricsTextEdit")
        self.gridLayout.addWidget(self.LyricsTextEdit, 7, 0, 1, 1)
        self.VerseOrderEdit = QtGui.QLineEdit(self.TextWidget)
        self.VerseOrderEdit.setObjectName("VerseOrderEdit")
        self.gridLayout.addWidget(self.VerseOrderEdit, 5, 0, 1, 1)
        self.VerseOrderLabel = QtGui.QLabel(self.TextWidget)
        self.VerseOrderLabel.setObjectName("VerseOrderLabel")
        self.gridLayout.addWidget(self.VerseOrderLabel, 4, 0, 1, 1)
        self.Selectedroup = QtGui.QWidget(self.TopWidget)
        self.Selectedroup.setGeometry(QtCore.QRect(329, 0, 381, 531))
        self.Selectedroup.setObjectName("Selectedroup")
        self.AuthorsGroupBox = QtGui.QGroupBox(self.Selectedroup)
        self.AuthorsGroupBox.setGeometry(QtCore.QRect(0, 0, 381, 66))
        self.AuthorsGroupBox.setObjectName("AuthorsGroupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.AuthorsGroupBox)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AuthorsSelectionComboItem = QtGui.QComboBox(self.AuthorsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AuthorsSelectionComboItem.sizePolicy().hasHeightForWidth())
        self.AuthorsSelectionComboItem.setSizePolicy(sizePolicy)
        self.AuthorsSelectionComboItem.setEditable(False)
        self.AuthorsSelectionComboItem.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.AuthorsSelectionComboItem.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.AuthorsSelectionComboItem.setMinimumContentsLength(8)
        self.AuthorsSelectionComboItem.setObjectName("AuthorsSelectionComboItem")
        self.horizontalLayout.addWidget(self.AuthorsSelectionComboItem)
        self.AuthorAddtoSongItem = QtGui.QPushButton(self.AuthorsGroupBox)
        self.AuthorAddtoSongItem.setMaximumSize(QtCore.QSize(110, 16777215))
        self.AuthorAddtoSongItem.setObjectName("AuthorAddtoSongItem")
        self.horizontalLayout.addWidget(self.AuthorAddtoSongItem)
        self.AddAuthorsButton = QtGui.QPushButton(self.AuthorsGroupBox)
        self.AddAuthorsButton.setObjectName("AddAuthorsButton")
        self.horizontalLayout.addWidget(self.AddAuthorsButton)
        self.SongBookGroup = QtGui.QGroupBox(self.Selectedroup)
        self.SongBookGroup.setGeometry(QtCore.QRect(0, 65, 381, 61))
        self.SongBookGroup.setObjectName("SongBookGroup")
        self.gridLayout_2 = QtGui.QGridLayout(self.SongBookGroup)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SongbookCombo = QtGui.QComboBox(self.SongBookGroup)
        self.SongbookCombo.setObjectName("SongbookCombo")
        self.gridLayout_2.addWidget(self.SongbookCombo, 0, 0, 1, 1)
        self.AddSongBookButton = QtGui.QPushButton(self.SongBookGroup)
        self.AddSongBookButton.setObjectName("AddSongBookButton")
        self.gridLayout_2.addWidget(self.AddSongBookButton, 0, 1, 1, 1)
        self.TopicGroupBox = QtGui.QGroupBox(self.Selectedroup)
        self.TopicGroupBox.setGeometry(QtCore.QRect(0, 130, 381, 66))
        self.TopicGroupBox.setObjectName("TopicGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.TopicGroupBox)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SongTopicCombo = QtGui.QComboBox(self.TopicGroupBox)
        self.SongTopicCombo.setObjectName("SongTopicCombo")
        self.gridLayout_3.addWidget(self.SongTopicCombo, 0, 0, 1, 1)
        self.AddTopicsToSongButton = QtGui.QPushButton(self.TopicGroupBox)
        self.AddTopicsToSongButton.setObjectName("AddTopicsToSongButton")
        self.gridLayout_3.addWidget(self.AddTopicsToSongButton, 0, 1, 1, 1)
        self.AddTopicButton = QtGui.QPushButton(self.TopicGroupBox)
        self.AddTopicButton.setObjectName("AddTopicButton")
        self.gridLayout_3.addWidget(self.AddTopicButton, 0, 2, 1, 1)
        self.SelectedAuthorGroupBox = QtGui.QGroupBox(self.Selectedroup)
        self.SelectedAuthorGroupBox.setGeometry(QtCore.QRect(0, 200, 191, 231))
        self.SelectedAuthorGroupBox.setObjectName("SelectedAuthorGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.SelectedAuthorGroupBox)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AuthorsListView = QtGui.QTableWidget(self.SelectedAuthorGroupBox)
        self.AuthorsListView.setAlternatingRowColors(True)
        self.AuthorsListView.setObjectName("AuthorsListView")
        self.AuthorsListView.setColumnCount(0)
        self.AuthorsListView.setRowCount(0)
        self.verticalLayout.addWidget(self.AuthorsListView)
        self.AuthorRemoveItem = QtGui.QPushButton(self.SelectedAuthorGroupBox)
        self.AuthorRemoveItem.setObjectName("AuthorRemoveItem")
        self.verticalLayout.addWidget(self.AuthorRemoveItem)
        self.SelectedTopicGroupBox = QtGui.QGroupBox(self.Selectedroup)
        self.SelectedTopicGroupBox.setGeometry(QtCore.QRect(190, 200, 181, 231))
        self.SelectedTopicGroupBox.setObjectName("SelectedTopicGroupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.SelectedTopicGroupBox)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setMargin(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ToticsListView = QtGui.QTableWidget(self.SelectedTopicGroupBox)
        self.ToticsListView.setAlternatingRowColors(True)
        self.ToticsListView.setObjectName("ToticsListView")
        self.ToticsListView.setColumnCount(0)
        self.ToticsListView.setRowCount(0)
        self.verticalLayout_2.addWidget(self.ToticsListView)
        self.pushButton = QtGui.QPushButton(self.SelectedTopicGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.CopyrightgroupBox = QtGui.QGroupBox(self.Selectedroup)
        self.CopyrightgroupBox.setGeometry(QtCore.QRect(0, 430, 371, 95))
        self.CopyrightgroupBox.setObjectName("CopyrightgroupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.CopyrightgroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CopyrightEditItem = QtGui.QLineEdit(self.CopyrightgroupBox)
        self.CopyrightEditItem.setObjectName("CopyrightEditItem")
        self.gridLayout_4.addWidget(self.CopyrightEditItem, 0, 0, 1, 1)
        self.CCLLabel = QtGui.QLabel(self.CopyrightgroupBox)
        self.CCLLabel.setObjectName("CCLLabel")
        self.gridLayout_4.addWidget(self.CCLLabel, 1, 0, 1, 1)
        self.CCLNumberEdit = QtGui.QLineEdit(self.CopyrightgroupBox)
        self.CCLNumberEdit.setObjectName("CCLNumberEdit")
        self.gridLayout_4.addWidget(self.CCLNumberEdit, 1, 1, 1, 1)
        self.CopyrightInsertItem = QtGui.QPushButton(self.CopyrightgroupBox)
        self.CopyrightInsertItem.setMaximumSize(QtCore.QSize(29, 16777215))
        self.CopyrightInsertItem.setObjectName("CopyrightInsertItem")
        self.gridLayout_4.addWidget(self.CopyrightInsertItem, 0, 1, 1, 1)
        self.ThemeGroupBox = QtGui.QGroupBox(self.TopWidget)
        self.ThemeGroupBox.setGeometry(QtCore.QRect(0, 630, 711, 66))
        self.ThemeGroupBox.setObjectName("ThemeGroupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.ThemeGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ThemeSelectionComboItem = QtGui.QComboBox(self.ThemeGroupBox)
        self.ThemeSelectionComboItem.setObjectName("ThemeSelectionComboItem")
        self.horizontalLayout_2.addWidget(self.ThemeSelectionComboItem)
        self.ThemeAddItem = QtGui.QPushButton(self.ThemeGroupBox)
        self.ThemeAddItem.setMaximumSize(QtCore.QSize(110, 16777215))
        self.ThemeAddItem.setObjectName("ThemeAddItem")
        self.horizontalLayout_2.addWidget(self.ThemeAddItem)
        self.CommentGroup = QtGui.QGroupBox(self.TopWidget)
        self.CommentGroup.setGeometry(QtCore.QRect(10, 530, 701, 111))
        self.CommentGroup.setObjectName("CommentGroup")
        self.gridLayout_5 = QtGui.QGridLayout(self.CommentGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CommentsEdit = QtGui.QTextEdit(self.CommentGroup)
        self.CommentsEdit.setObjectName("CommentsEdit")
        self.gridLayout_5.addWidget(self.CommentsEdit, 0, 0, 1, 1)
        self.ButtonBox = QtGui.QDialogButtonBox(EditSongDialog)
        self.ButtonBox.setGeometry(QtCore.QRect(570, 720, 156, 27))
        self.ButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.ButtonBox.setObjectName("ButtonBox")

        self.retranslateUi(EditSongDialog)
        QtCore.QObject.connect(self.ButtonBox, QtCore.SIGNAL("rejected()"), EditSongDialog.close)
        QtCore.QObject.connect(self.ButtonBox, QtCore.SIGNAL("accepted()"), EditSongDialog.close)
        QtCore.QMetaObject.connectSlotsByName(EditSongDialog)

    def retranslateUi(self, EditSongDialog):
        EditSongDialog.setWindowTitle(QtGui.QApplication.translate("EditSongDialog", "Song Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.TitleLabel.setText(QtGui.QApplication.translate("EditSongDialog", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.AlternativeTitleLabel.setText(QtGui.QApplication.translate("EditSongDialog", "Alternative Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.LyricsLabel.setText(QtGui.QApplication.translate("EditSongDialog", "Lyrics:", None, QtGui.QApplication.UnicodeUTF8))
        self.VerseOrderLabel.setText(QtGui.QApplication.translate("EditSongDialog", "Verse Order:", None, QtGui.QApplication.UnicodeUTF8))
        self.AuthorsGroupBox.setTitle(QtGui.QApplication.translate("EditSongDialog", "Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.AuthorAddtoSongItem.setText(QtGui.QApplication.translate("EditSongDialog", "Add to Song", None, QtGui.QApplication.UnicodeUTF8))
        self.AddAuthorsButton.setText(QtGui.QApplication.translate("EditSongDialog", "Add Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.SongBookGroup.setTitle(QtGui.QApplication.translate("EditSongDialog", "SongBook", None, QtGui.QApplication.UnicodeUTF8))
        self.AddSongBookButton.setText(QtGui.QApplication.translate("EditSongDialog", "Add Song Book", None, QtGui.QApplication.UnicodeUTF8))
        self.TopicGroupBox.setTitle(QtGui.QApplication.translate("EditSongDialog", "Topic", None, QtGui.QApplication.UnicodeUTF8))
        self.AddTopicsToSongButton.setText(QtGui.QApplication.translate("EditSongDialog", "Add to Song", None, QtGui.QApplication.UnicodeUTF8))
        self.AddTopicButton.setText(QtGui.QApplication.translate("EditSongDialog", "Add Topic", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectedAuthorGroupBox.setTitle(QtGui.QApplication.translate("EditSongDialog", "Selected Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.AuthorRemoveItem.setText(QtGui.QApplication.translate("EditSongDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectedTopicGroupBox.setTitle(QtGui.QApplication.translate("EditSongDialog", "Selected Topics", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("EditSongDialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.CopyrightgroupBox.setTitle(QtGui.QApplication.translate("EditSongDialog", "Copyright Infomaton", None, QtGui.QApplication.UnicodeUTF8))
        self.CCLLabel.setText(QtGui.QApplication.translate("EditSongDialog", "CCL Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.CopyrightInsertItem.setText(QtGui.QApplication.translate("EditSongDialog", "©", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeGroupBox.setTitle(QtGui.QApplication.translate("EditSongDialog", "Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.ThemeAddItem.setText(QtGui.QApplication.translate("EditSongDialog", "Add a Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.CommentGroup.setTitle(QtGui.QApplication.translate("EditSongDialog", "Comments", None, QtGui.QApplication.UnicodeUTF8))

