# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'songbookdialog.ui'
#
# Created: Sun Jan  4 08:43:12 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from openlp.plugins.songs.lib import TextListData

class Ui_SongBookDialog(object):
    def setupUi(self, SongBookDialog):
        SongBookDialog.setObjectName("SongBookDialog")
        SongBookDialog.resize(387, 531)
        self.DialogLayout = QtGui.QVBoxLayout(SongBookDialog)
        self.DialogLayout.setSpacing(8)
        self.DialogLayout.setMargin(8)
        self.DialogLayout.setObjectName("DialogLayout")

        self.BookSongListView = QtGui.QListView()
        self.BookSongListView.setAlternatingRowColors(True)
        self.BookSongListData = TextListData()
        self.BookSongListView.setModel(self.BookSongListData)
        self.DialogLayout.addWidget(self.BookSongListView)

        self.DialogLayout.addWidget(self.BookSongListView)
        self.SongBookGroup = QtGui.QGroupBox(SongBookDialog)
        self.SongBookGroup.setMinimumSize(QtCore.QSize(0, 200))
        self.SongBookGroup.setObjectName("SongBookGroup")
        self.SongBookLayout = QtGui.QVBoxLayout(self.SongBookGroup)
        self.SongBookLayout.setSpacing(8)
        self.SongBookLayout.setMargin(8)
        self.SongBookLayout.setObjectName("SongBookLayout")
        self.DetailsWidget = QtGui.QWidget(self.SongBookGroup)
        self.DetailsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.DetailsWidget.setObjectName("DetailsWidget")
        self.DetailsLayout = QtGui.QFormLayout(self.DetailsWidget)
        self.DetailsLayout.setMargin(0)
        self.DetailsLayout.setSpacing(8)
        self.DetailsLayout.setObjectName("DetailsLayout")
        self.NameLabel = QtGui.QLabel(self.DetailsWidget)
        self.NameLabel.setObjectName("NameLabel")
        self.DetailsLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.NameLabel)
        self.NameEdit = QtGui.QLineEdit(self.DetailsWidget)
        self.NameEdit.setObjectName("NameEdit")
        self.DetailsLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.NameEdit)
        self.PublisherLabel = QtGui.QLabel(self.DetailsWidget)
        self.PublisherLabel.setObjectName("PublisherLabel")
        self.DetailsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.PublisherLabel)
        self.PublisherEdit = QtGui.QLineEdit(self.DetailsWidget)
        self.PublisherEdit.setObjectName("PublisherEdit")
        self.DetailsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.PublisherEdit)
        self.SongBookLayout.addWidget(self.DetailsWidget)
        self.MessageLabel = QtGui.QLabel(self.SongBookGroup)
        self.MessageLabel.setObjectName("MessageLabel")
        self.SongBookLayout.addWidget(self.MessageLabel)
        self.ButtonWidget = QtGui.QWidget(self.SongBookGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonWidget.sizePolicy().hasHeightForWidth())
        self.ButtonWidget.setSizePolicy(sizePolicy)
        self.ButtonWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.ButtonWidget.setObjectName("ButtonWidget")
        self.ButtonLayout = QtGui.QHBoxLayout(self.ButtonWidget)
        self.ButtonLayout.setSpacing(8)
        self.ButtonLayout.setMargin(0)
        self.ButtonLayout.setObjectName("ButtonLayout")
        spacerItem = QtGui.QSpacerItem(61, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ButtonLayout.addItem(spacerItem)
        self.ClearButton = QtGui.QPushButton(self.ButtonWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/services/service_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClearButton.setIcon(icon)
        self.ClearButton.setObjectName("ClearButton")
        self.ButtonLayout.addWidget(self.ClearButton)
        self.AddUpdateButton = QtGui.QPushButton(self.ButtonWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/services/service_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddUpdateButton.setIcon(icon1)
        self.AddUpdateButton.setObjectName("AddUpdateButton")
        self.ButtonLayout.addWidget(self.AddUpdateButton)
        self.DeleteButton = QtGui.QPushButton(self.ButtonWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/services/service_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteButton.setIcon(icon2)
        self.DeleteButton.setObjectName("DeleteButton")
        self.ButtonLayout.addWidget(self.DeleteButton)
        self.SongBookLayout.addWidget(self.ButtonWidget)
        self.DialogLayout.addWidget(self.SongBookGroup)
        self.ButtonBox = QtGui.QDialogButtonBox(SongBookDialog)
        self.ButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.ButtonBox.setObjectName("ButtonBox")
        self.DialogLayout.addWidget(self.ButtonBox)

        self.retranslateUi(SongBookDialog)
        QtCore.QObject.connect(self.ButtonBox, QtCore.SIGNAL("accepted()"), SongBookDialog.accept)
        QtCore.QObject.connect(self.ButtonBox, QtCore.SIGNAL("rejected()"), SongBookDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SongBookDialog)

    def retranslateUi(self, SongBookDialog):
        SongBookDialog.setWindowTitle(QtGui.QApplication.translate("SongBookDialog", "Book Song Maintenance", None, QtGui.QApplication.UnicodeUTF8))
        self.SongBookGroup.setTitle(QtGui.QApplication.translate("SongBookDialog", "Song Book", None, QtGui.QApplication.UnicodeUTF8))
        self.NameLabel.setText(QtGui.QApplication.translate("SongBookDialog", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.PublisherLabel.setText(QtGui.QApplication.translate("SongBookDialog", "Publisher:", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearButton.setToolTip(QtGui.QApplication.translate("SongBookDialog", "Clear Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearButton.setText(QtGui.QApplication.translate("SongBookDialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.AddUpdateButton.setToolTip(QtGui.QApplication.translate("SongBookDialog", "Add Update Author", None, QtGui.QApplication.UnicodeUTF8))
        self.AddUpdateButton.setText(QtGui.QApplication.translate("SongBookDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteButton.setToolTip(QtGui.QApplication.translate("SongBookDialog", "Delete Author", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteButton.setText(QtGui.QApplication.translate("SongBookDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
